//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate;

@interface _TtC12MMFoundation20KaraImageMessageInfo : NSObject
{
    // Error parsing type: , name: revisionTime
    // Error parsing type: , name: numberOfBehaviors
    // Error parsing type: , name: loss
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) double loss; // @synthesize loss;
@property(nonatomic) long long numberOfBehaviors; // @synthesize numberOfBehaviors;
@property(nonatomic, copy) NSDate *revisionTime;

@end

