//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Kara5Model.h"

@interface _TtC4Kara14UpdatableModel : _TtC4Kara5Model
{
    // Error parsing type: , name: urlOfUpdatedModel
    // Error parsing type: , name: task
}

@end

