//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC12MMFoundation26KaraImageMessagePrediction : NSObject
{
    // Error parsing type: , name: svrid
    // Error parsing type: , name: session
    // Error parsing type: , name: timestamp
    // Error parsing type: , name: download
    // Error parsing type: , name: possibility
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) double possibility; // @synthesize possibility;
@property(nonatomic) _Bool download; // @synthesize download;
@property(nonatomic) long long timestamp; // @synthesize timestamp;
@property(nonatomic, copy) NSString *session;
@property(nonatomic) long long svrid; // @synthesize svrid;

@end

