//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _YYModelPropertyMeta;

@interface _YYModelPropertyMapperNode : NSObject
{
    basic_string_90719d97 *_tag;
    _YYModelPropertyMeta *_propertyMeta;
    _Bool _isXmlAttribute;
    _YYModelPropertyMapperNode *_firstChildNode;
    _YYModelPropertyMapperNode *_nextSibling;
    CDUnknownBlockType _preProcess;
    _YYModelPropertyMapperNode *_parentNode;
}

@property(nonatomic) __weak _YYModelPropertyMapperNode *parentNode; // @synthesize parentNode=_parentNode;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

