//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BrandTimelineMsgDBResortItem : NSObject
{
    _Bool _bShowBigPic;
    unsigned int _predict;
    unsigned long long _seqId;
}

@property(nonatomic) _Bool bShowBigPic; // @synthesize bShowBigPic=_bShowBigPic;
@property(nonatomic) unsigned int predict; // @synthesize predict=_predict;
@property(nonatomic) unsigned long long seqId; // @synthesize seqId=_seqId;
- (id)description;

@end

