//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIWindow.h"

#import "MMUIViewControllerExt-Protocol.h"

@class BTFeedbackPanelCoordinateParams, BTFeedbackPanelInitParams, MMUIImageView, MMUILabel, MMUIView, NSMutableArray, NSString, UIButton;
@protocol BTFeedbackPanelDelegate;

@interface BTFeedbackPanel : MMUIWindow <MMUIViewControllerExt>
{
    BTFeedbackPanelInitParams *m_initParams;
    BTFeedbackPanelCoordinateParams *m_coordinateParams;
    MMUIView *m_backgroundView;
    MMUIImageView *m_indicatorView;
    MMUIView *m_pannelView;
    MMUIView *m_reasonBtnContainerView;
    MMUILabel *m_titleView;
    UIButton *m_confirmBtn;
    NSMutableArray *m_reasonBtnArr;
    NSMutableArray *m_selectedBtnArr;
    id <BTFeedbackPanelDelegate> _panelDelegate;
}

@property(nonatomic) __weak id <BTFeedbackPanelDelegate> panelDelegate; // @synthesize panelDelegate=_panelDelegate;
- (void).cxx_destruct;
- (void)hide;
- (void)show;
- (void)onClickConfirmBtn;
- (void)onClickReasonBtn:(id)arg1;
- (void)onTapBackground;
- (void)layoutPanelView;
- (void)layoutSubviews;
- (void)MMUIViewControllerWillAppear:(id)arg1;
- (id)genReasonBtnWithReason:(id)arg1;
- (void)initReasonBtns;
- (void)addCornersToPannelView;
- (void)initView;
- (void)checkAndSetCoordinateParams:(id)arg1;
- (void)checkAndSetInitParams:(id)arg1;
- (id)initWithInitParams:(id)arg1 coordinateParams:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

