//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BTFeedbackPanelCoordinateParams : NSObject
{
    double _pannelViewWidth;
    unsigned long long _pannelViewAlignType;
    double _pannelViewAlignMargin;
    double _downsidePanelY;
    double _upsidePanelY;
    double _indicatorViewX;
}

@property(nonatomic) double indicatorViewX; // @synthesize indicatorViewX=_indicatorViewX;
@property(nonatomic) double upsidePanelY; // @synthesize upsidePanelY=_upsidePanelY;
@property(nonatomic) double downsidePanelY; // @synthesize downsidePanelY=_downsidePanelY;
@property(nonatomic) double pannelViewAlignMargin; // @synthesize pannelViewAlignMargin=_pannelViewAlignMargin;
@property(nonatomic) unsigned long long pannelViewAlignType; // @synthesize pannelViewAlignType=_pannelViewAlignType;
@property(nonatomic) double pannelViewWidth; // @synthesize pannelViewWidth=_pannelViewWidth;

@end

