//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BTMsgSectionData.h"

#import "BTReaderItemCellViewModelDelegate-Protocol.h"

@class CContact, NSString;

@interface BTReaderMsgSectionData : BTMsgSectionData <BTReaderItemCellViewModelDelegate>
{
    CContact *_contact;
    _Bool _bIsBrandSettingFold;
    _Bool _isOftenReadContact;
    _Bool _isStarContact;
    _Bool _isRemoveMsgTime;
}

+ (_Bool)canCreateSectionDataWithMsgWrap:(id)arg1;
@property(nonatomic) _Bool isRemoveMsgTime; // @synthesize isRemoveMsgTime=_isRemoveMsgTime;
@property(readonly, nonatomic) _Bool isStarContact; // @synthesize isStarContact=_isStarContact;
@property(readonly, nonatomic) _Bool isOftenReadContact; // @synthesize isOftenReadContact=_isOftenReadContact;
@property(readonly, nonatomic) _Bool bIsBrandSettingFold; // @synthesize bIsBrandSettingFold=_bIsBrandSettingFold;
@property(readonly, nonatomic) CContact *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;
- (void)onItemViewModelViewHeightChange:(id)arg1;
@property(readonly, nonatomic) unsigned int expanState;
@property(readonly, nonatomic) unsigned int lastIdx;
@property(readonly, nonatomic) unsigned long long firstMid;
@property(readonly, nonatomic) NSString *bizUsername;
@property(readonly, nonatomic) _Bool isTopItemShowLargeCover;
- (_Bool)isBrowsed;
@property(readonly, nonatomic) _Bool bIsExpand;
- (unsigned long long)sequenceId;
- (id)arrReaderItemCellViewModel;
@property(readonly, nonatomic) unsigned long long itemShowCount;
- (void)updateContact:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isFold;
- (void)updateItemViewModelArr;
- (void)initItemViewModelArr;
- (void)setSectionWidth:(double)arg1;
- (double)heightForRowInSection:(unsigned long long)arg1;
- (long long)numberOfRowsInSection;
- (unsigned long long)sectionType;
- (void)updateMsgWrap:(id)arg1;
- (id)initWithMsgWrap:(id)arg1 sectionWidth:(double)arg2 displayMode:(unsigned int)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

