//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MMUIImageView, MMUILabel;

@interface ChatRoomToolWeAppEmptyCollectionCell : UICollectionViewCell
{
    MMUIImageView *m_imageView;
    MMUILabel *m_titleLabel;
}

+ (double)getCellHeight;
- (void).cxx_destruct;
- (void)initTitleLabel;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

