//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IGroupMgrExt-Protocol.h"
#import "ILinkEventExt-Protocol.h"
#import "MMAcceptAgreementResultViewControllerDelegate-Protocol.h"

@class CContact, MMHeadImageView, MMImageView, MMUILabel, NSString, RichTextView, UIButton;

@interface ChatRoomUpgradeOpenIMViewController : MMUIViewController <MMAcceptAgreementResultViewControllerDelegate, ILinkEventExt, IGroupMgrExt>
{
    MMUILabel *m_topTitleLabel;
    NSString *m_topTitleText;
    UIButton *m_iAcceptBtn;
    RichTextView *m_titleTextView;
    MMUILabel *m_contentTextLabel;
    MMHeadImageView *m_headImageView;
    MMUILabel *m_nickNameTextLabel;
    MMImageView *m_namePostIconView;
    unsigned int _m_scene;
    CContact *m_chatRoomContact;
    NSString *m_titleText;
    NSString *m_contentText;
}

@property(nonatomic) unsigned int m_scene; // @synthesize m_scene=_m_scene;
@property(retain, nonatomic) NSString *m_topTitleText; // @synthesize m_topTitleText;
@property(retain, nonatomic) NSString *m_contentText; // @synthesize m_contentText;
@property(retain, nonatomic) NSString *m_titleText; // @synthesize m_titleText;
@property(retain, nonatomic) CContact *m_chatRoomContact; // @synthesize m_chatRoomContact;
- (void).cxx_destruct;
- (void)reportUpgradeChatRoomOperateWithGroupUserName:(id)arg1 upgradeChatRoomOperateResult:(unsigned int)arg2 upgradeChatRoomShowSystemMessageTyp:(unsigned int)arg3;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)OnUpgradeAssociateChatRoom:(id)arg1 withResult:(unsigned int)arg2 errorMsg:(id)arg3;
- (void)onClickMakeSureActionWithViewController:(id)arg1;
- (void)onCancel;
- (void)doIAccept;
- (void)layoutIAcceptBtn;
- (void)layoutContentTextLabel;
- (void)layoutTitleTextView;
- (void)layoutHeadView;
- (void)layoutTopTitleLable;
- (void)layoutView;
- (void)setUpNavigation;
- (void)viewWillLayoutSubviews;
- (void)initData;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

