//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "IGroupMgrExt-Protocol.h"
#import "IMsgExt-Protocol.h"

@class ChatRoomFamilyEdcationDataPB, NSDictionary, NSRecursiveLock;

@interface ChatRoomToolMgr : MMObject <IGroupMgrExt, IMsgExt>
{
    NSRecursiveLock *m_oLock;
    NSDictionary *m_nativeWeAppIconUrlDic;
    NSDictionary *m_nativeWeAppNickNameDic;
    ChatRoomFamilyEdcationDataPB *m_chatRoomFamilyEdcationData;
}

- (void).cxx_destruct;
- (void)onUpdateChatRoomtToolWeAppInfoListWithUserName:(id)arg1 roomToolsWxApps:(id)arg2 withResult:(unsigned int)arg3 errorMsg:(id)arg4;
- (long long)getGroupRoleWithGroupUserName:(id)arg1;
- (void)reportChatRoomToolEditWithGroupUserName:(id)arg1 andExitType:(unsigned long long)arg2 andTopBefore:(long long)arg3 andTopAfter:(long long)arg4;
- (void)reportChatRoomToolClickWeApptWithGroupUserName:(id)arg1 weAppInfo:(id)arg2 isTop:(_Bool)arg3;
- (void)reportChatRoomToolAttachmentClickWithGroupUserName:(id)arg1 andTopCount:(long long)arg2 andUsedCount:(long long)arg3;
- (void)reportChatRoomToolAttachmentExposureWithGroupUserName:(id)arg1;
- (id)getC2CAAChatRoomToolWeAppInfo;
- (_Bool)isC2CAAMsgWrap:(id)arg1;
- (void)updateChatRoomtToolWeAppInfoListFromRoomToolsWxApp:(id)arg1 roomToolsWxApp:(id)arg2;
- (id)getWeAppInfoListWithUserName:(id)arg1;
- (_Bool)updateChatRoomtToolWeAppInfoListWithUserName:(id)arg1 weAppInfoList:(id)arg2;
- (id)getMMKVUpdateChatRoomtToolWeAppHadGetContactArKey;
- (void)setUpdateFamilyChatRoomtToolHadGetContactDetail:(id)arg1;
- (_Bool)checkUpdateFamilyChatRoomtToolHadNeedGetContactDetail:(id)arg1;
- (id)genChatRoomToolWeAppInfoWithMessageWrap:(id)arg1;
- (_Bool)isWeAppMsgWithMessageWrap:(id)arg1;
- (id)getNativeWeAppInfoList;
- (id)getNickNameWithAppUserName:(id)arg1;
- (id)getIconUrlWithAppUserName:(id)arg1;
- (_Bool)isNativeWeAppWithAppUserName:(id)arg1;
- (_Bool)isNativeWeApp:(id)arg1;
- (_Bool)weAppListContainsObject:(id)arg1 andObject:(id)arg2;
- (void)initData;
- (void)dealloc;
- (void)initRegister;
- (id)init;

@end

