//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MMHeadImageView, OldAccountContact, UIButton, UILabel, UIView;
@protocol ContactsImportTableViewCellDelegate;

@interface ContactsImportTableViewCell : UITableViewCell
{
    OldAccountContact *_oldAccountContact;
    id <ContactsImportTableViewCellDelegate> _delegate;
    MMHeadImageView *_headImageView;
    UILabel *_nicknameLabel;
    UIButton *_addButton;
    UILabel *_addedLabel;
    UIView *_separatorView;
}

@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UILabel *addedLabel; // @synthesize addedLabel=_addedLabel;
@property(retain, nonatomic) UIButton *addButton; // @synthesize addButton=_addButton;
@property(retain, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) MMHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(nonatomic) __weak id <ContactsImportTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) OldAccountContact *oldAccountContact; // @synthesize oldAccountContact=_oldAccountContact;
- (void).cxx_destruct;
- (void)onTapAddButton;
- (void)layoutSubviews;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

