//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ContactsImportLogic, NSArray, NSString;

@protocol ContactsImportLogicDelegate <NSObject>

@optional
- (void)onFetchContactListFailed:(ContactsImportLogic *)arg1;
- (void)onFetchContactListSucceeded:(ContactsImportLogic *)arg1 appendContactList:(NSArray *)arg2 isFinished:(_Bool)arg3;
- (void)onBindOldWechatAccountFailed:(ContactsImportLogic *)arg1 errorMessage:(NSString *)arg2 canRecover:(_Bool)arg3;
- (void)onBindOldWechatAccountSucceeded:(ContactsImportLogic *)arg1;
@end

