//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface DBContactChatRoomToolWeApp : NSObject <WCTTableCoding>
{
    NSString *_userName;
    NSString *_appUserName;
    NSString *_appPagePath;
}

+ (void)__wcdb_table_constraint_33:(struct WCTBinding *)arg1;
+ (void)__wcdb_table_constraint_32:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_31:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_30:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_29:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)appPagePath;
+ (const struct WCTProperty *)__wcdb_synthesize_28:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)appUserName;
+ (const struct WCTProperty *)__wcdb_synthesize_27:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)userName;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *appPagePath; // @synthesize appPagePath=_appPagePath;
@property(retain, nonatomic) NSString *appUserName; // @synthesize appUserName=_appUserName;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

