//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ABTestItem, NSArray, NSString;

@protocol EmoticonInputRecommendMgrExt <NSObject>
- (void)onMergeRecommendEmoticon:(NSString *)arg1 emoticonWrapList:(NSArray *)arg2 abTestItem:(ABTestItem *)arg3 sessionId:(NSString *)arg4;
@end

