//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "EmoticonBoardCrossCollectionBasePageCell.h"

#import "IStoreEmotionDesignerReddotMgrExt-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"

@class EmoticonBoardCrossCollectionEmoticonHeaderModel, EmoticonBoardCrossCollectionEmoticonHeaderView, NSIndexPath, NSString, StoreEmotionGetDetailCgi, UILongPressGestureRecognizer;
@protocol EmoticonBoardCrossCollectionEmoticonPageDelegate;

@interface EmoticonBoardCrossCollectionEmoticonPageCell : EmoticonBoardCrossCollectionBasePageCell <UICollectionViewDataSource, IStoreEmotionDesignerReddotMgrExt>
{
    _Bool _hasDescription;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    NSIndexPath *_selectedIndexPath;
    StoreEmotionGetDetailCgi *_getEmotionDetailCgi;
    EmoticonBoardCrossCollectionEmoticonHeaderModel *_headerViewModel;
    EmoticonBoardCrossCollectionEmoticonHeaderView *_headerView;
}

@property(nonatomic) __weak EmoticonBoardCrossCollectionEmoticonHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) EmoticonBoardCrossCollectionEmoticonHeaderModel *headerViewModel; // @synthesize headerViewModel=_headerViewModel;
@property(retain, nonatomic) StoreEmotionGetDetailCgi *getEmotionDetailCgi; // @synthesize getEmotionDetailCgi=_getEmotionDetailCgi;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(nonatomic) _Bool hasDescription; // @synthesize hasDescription=_hasDescription;
- (void).cxx_destruct;
- (void)onDesignerPersonalInfoUpdated:(id)arg1;
- (void)onDesigner:(id)arg1 changReddotStatus:(_Bool)arg2 newReddotPids:(id)arg3;
- (void)reloadHeader;
- (void)configHeaderModelUpdateLogic;
- (void)configHeaderModel;
- (void)bindHeaderView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (_Bool)isCustomOrCameraPid:(id)arg1;
- (_Bool)isCameraPid:(id)arg1;
- (_Bool)isCustomPid:(id)arg1;
- (void)onLongPressToPreview:(id)arg1;
- (void)setSectionInfo:(id)arg1;
- (unsigned long long)maximumNumberOfItemsInRow;
- (void)configGestureRecognizer;
- (void)configCollectionViewWithFrame:(struct CGRect)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <EmoticonBoardCrossCollectionEmoticonPageDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

