//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface EmoticonReportData : MMObject
{
}

+ (void)ReportRedotExposeActionWithEnterPid:(id)arg1 index:(int)arg2;
+ (void)ReportRedotAction:(int)arg1 isRed:(int)arg2 enterPid:(id)arg3 index:(int)arg4 pid:(id)arg5;
+ (void)ReportFastManagementAction:(int)arg1 scene:(int)arg2 pid:(id)arg3 md5:(id)arg4 index:(int)arg5;
+ (void)ReportSendGifWithDatalength:(unsigned int)arg1 md5:(id)arg2 scene:(unsigned long long)arg3;
+ (void)ReportSelectGifFailedWithDatalength:(unsigned int)arg1 scene:(unsigned long long)arg2;
+ (void)ReportEmoticonAction:(unsigned long long)arg1 newScene:(long long)arg2 searchEmotWrap:(id)arg3;
+ (void)ReportEmoticonAction:(unsigned long long)arg1 scene:(unsigned long long)arg2 messageWrap:(id)arg3 newScene:(long long)arg4 sessionID:(id)arg5;
+ (void)ReportEmoticonAction:(unsigned long long)arg1 scene:(unsigned long long)arg2 messageWrap:(id)arg3;
+ (void)ReportEmoticonDownloadFromQrcode;
+ (void)ReportEmoticonDownloadFromNodeView;
+ (void)ReportEmoticonDownloadFromSns;
+ (void)ReportEmoticonDownloadFromPreview;
+ (void)ReportEmoticonBoardShowClick;

@end

