//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWindowViewController.h"

#import "EmoticonBackupOperateMgrExt-Protocol.h"

@class EmoticonPreviewModel, HLActionButton, MMEmoticonView, NSString, UIImage, UIImageView, UILabel, UIView;
@protocol EmoticonPreviewWindowViewControllerDelegate;

@interface EmoticonPreviewWindowViewController : MMWindowViewController <EmoticonBackupOperateMgrExt>
{
    int _aligment;
    id <EmoticonPreviewWindowViewControllerDelegate> _delegate;
    EmoticonPreviewModel *_model;
    UIImageView *_popoverView;
    MMEmoticonView *_playerView;
    UIView *_playerViewContainer;
    UILabel *_descriptionLabel;
    HLActionButton *_moveToFrontButton;
    HLActionButton *_deleteButton;
    HLActionButton *_showDetailButton;
    HLActionButton *_confirmDelButton;
    UIView *_horizontalDivider;
    UIView *_verticalDivider;
    UIImage *_leftTipsBubble;
    UIImage *_rightTipsBubble;
    UIImage *_midTipsBubble;
    UIImageView *_leftButtonBubble;
    UIImageView *_rightButtonBubble;
    UIImageView *_midButtonBubble;
}

@property(retain, nonatomic) UIImageView *midButtonBubble; // @synthesize midButtonBubble=_midButtonBubble;
@property(retain, nonatomic) UIImageView *rightButtonBubble; // @synthesize rightButtonBubble=_rightButtonBubble;
@property(retain, nonatomic) UIImageView *leftButtonBubble; // @synthesize leftButtonBubble=_leftButtonBubble;
@property(retain, nonatomic) UIImage *midTipsBubble; // @synthesize midTipsBubble=_midTipsBubble;
@property(retain, nonatomic) UIImage *rightTipsBubble; // @synthesize rightTipsBubble=_rightTipsBubble;
@property(retain, nonatomic) UIImage *leftTipsBubble; // @synthesize leftTipsBubble=_leftTipsBubble;
@property(nonatomic) int aligment; // @synthesize aligment=_aligment;
@property(retain, nonatomic) UIView *verticalDivider; // @synthesize verticalDivider=_verticalDivider;
@property(retain, nonatomic) UIView *horizontalDivider; // @synthesize horizontalDivider=_horizontalDivider;
@property(retain, nonatomic) HLActionButton *confirmDelButton; // @synthesize confirmDelButton=_confirmDelButton;
@property(retain, nonatomic) HLActionButton *showDetailButton; // @synthesize showDetailButton=_showDetailButton;
@property(retain, nonatomic) HLActionButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) HLActionButton *moveToFrontButton; // @synthesize moveToFrontButton=_moveToFrontButton;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UIView *playerViewContainer; // @synthesize playerViewContainer=_playerViewContainer;
@property(retain, nonatomic) MMEmoticonView *playerView; // @synthesize playerView=_playerView;
@property(retain, nonatomic) UIImageView *popoverView; // @synthesize popoverView=_popoverView;
@property(retain, nonatomic) EmoticonPreviewModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <EmoticonPreviewWindowViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)currentEmotionMd5;
- (void)deleteEmoticon:(id)arg1;
- (_Bool)isSelfModEvent:(id)arg1;
- (void)onStickyBackupEmoticonFailed:(id)arg1;
- (void)onStickyBackupEmoticonOK:(id)arg1;
- (void)onDeleteBackupEmoticonFailed:(id)arg1;
- (void)onDeleteBackupEmoticonOK:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)onShowEmotionDetailPage:(id)arg1;
- (void)onMoveEmoticonToFront:(id)arg1;
- (void)onComfirmDeleteEmoticon:(id)arg1;
- (void)onDeleteEmoticon:(id)arg1;
- (void)changeToDeleteConfirmMode;
- (void)layoutSubviewFrame;
- (void)playEmotionGifIfNeed;
- (void)setPreviewModel:(id)arg1;
- (void)setupButtonBubbleImageLeft:(id)arg1 mid:(id)arg2 right:(id)arg3;
- (void)layoutButtonComponent;
- (id)actionButtonWithTitle:(id)arg1 selector:(SEL)arg2;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

