//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FavoritesModel.h"

@class NSString;

@interface FavProductItem : FavoritesModel
{
    NSString *_productTitle;
    NSString *_productDesc;
    NSString *_thumbUrl;
    NSString *_productInfo;
    NSString *_productSellerName;
    NSString *_productUrl;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) NSString *productUrl; // @synthesize productUrl=_productUrl;
@property(retain, nonatomic) NSString *productSellerName; // @synthesize productSellerName=_productSellerName;
@property(retain, nonatomic) NSString *productInfo; // @synthesize productInfo=_productInfo;
@property(retain, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(retain, nonatomic) NSString *productDesc; // @synthesize productDesc=_productDesc;
@property(retain, nonatomic) NSString *productTitle; // @synthesize productTitle=_productTitle;
- (void).cxx_destruct;

@end

