//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProductDetailViewController.h"

@class FavDataItemWrap, FavoritesItem;

@interface FavProductDetailViewController : ProductDetailViewController
{
    FavoritesItem *m_favItem;
    FavDataItemWrap *m_favDataWrap;
}

- (void).cxx_destruct;
- (void)OnSendAppMsgOKToContacts:(id)arg1;
- (void)onEditProductTag;
- (void)onDeleteProduct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithFavDataWrap:(id)arg1;
- (id)initWithFavoritesItem:(id)arg1;

@end

