//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FavoritesModel.h"

@class FavAppMsgShareItem, NSString;

@interface FavURLItem : FavoritesModel
{
    NSString *_pageTitle;
    NSString *_pageDesc;
    NSString *_thumbUrl;
    NSString *_canvasPageXml;
    NSString *_wsVideoFlowXml;
    FavAppMsgShareItem *_appMsgShareItem;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) FavAppMsgShareItem *appMsgShareItem; // @synthesize appMsgShareItem=_appMsgShareItem;
@property(retain, nonatomic) NSString *wsVideoFlowXml; // @synthesize wsVideoFlowXml=_wsVideoFlowXml;
@property(retain, nonatomic) NSString *canvasPageXml; // @synthesize canvasPageXml=_canvasPageXml;
@property(retain, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(retain, nonatomic) NSString *pageDesc; // @synthesize pageDesc=_pageDesc;
@property(retain, nonatomic) NSString *pageTitle; // @synthesize pageTitle=_pageTitle;
- (void).cxx_destruct;

@end

