//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FavoritesModel.h"

@class NSString;

@interface FavWeAppItem : FavoritesModel
{
    unsigned int _type;
    unsigned int _pkgType;
    NSString *_userName;
    NSString *_iconUrl;
    NSString *_pagePath;
    NSString *_sourceDisplayName;
    NSString *_appId;
}

@property(nonatomic) unsigned int pkgType; // @synthesize pkgType=_pkgType;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *sourceDisplayName; // @synthesize sourceDisplayName=_sourceDisplayName;
@property(copy, nonatomic) NSString *pagePath; // @synthesize pagePath=_pagePath;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;

@end

