//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewController.h"

#import "WKScriptMessageHandler-Protocol.h"

@class FavDataItemWrap, FavWebCacheContext, FavoritesItem, NSDictionary, NSString;

@interface FavWebViewController : MMWebViewController <WKScriptMessageHandler>
{
    FavoritesItem *m_favItem;
    FavDataItemWrap *m_favDataItemWrap;
    unsigned int m_dataFavId;
    _Bool m_hasAddHandler;
    _Bool m_hasCached;
    _Bool m_hasLoaded;
    FavWebCacheContext *m_cacheContext;
    NSDictionary *m_htmlAndFileUrlResult;
}

- (void).cxx_destruct;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (void)cacheWebContent;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)onWebViewEditTag;
- (void)onWebViewDelete;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithFavDataWrap:(id)arg1;
- (id)initWithFavoritesItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

