//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderRedDotCtrlInfo, NSString;

@interface FinderWxMentionCount : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int count; // @dynamic count;
@property(retain, nonatomic) FinderRedDotCtrlInfo *ctrlInfo; // @dynamic ctrlInfo;
@property(retain, nonatomic) NSString *headImgUrl; // @dynamic headImgUrl;
@property(nonatomic) unsigned int mentionCommentCount; // @dynamic mentionCommentCount;
@property(nonatomic) unsigned int mentionLikeCount; // @dynamic mentionLikeCount;
@property(nonatomic) unsigned int mentionNotificationCount; // @dynamic mentionNotificationCount;

@end

