//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WSPardusWebViewJSHandlerDelegate-Protocol.h"

@class FTSWebSearchPardusWebReportItem, MMUIViewController, NSString, WSPardusWebViewJSHandler, WSTemplateLogicController;
@protocol FTSWebSearchPardusWebHeaderViewDelegate;

@interface FTSWebSearchPardusWebHeaderView : UIView <WSPardusWebViewJSHandlerDelegate>
{
    _Bool _isWebViewReady;
    id <FTSWebSearchPardusWebHeaderViewDelegate> _delegate;
    MMUIViewController *_contentVC;
    FTSWebSearchPardusWebReportItem *_reportItem;
    WSTemplateLogicController *_logicController;
    WSPardusWebViewJSHandler *_jsHandler;
    NSString *_currentQuery;
}

@property(retain, nonatomic) NSString *currentQuery; // @synthesize currentQuery=_currentQuery;
@property(retain, nonatomic) WSPardusWebViewJSHandler *jsHandler; // @synthesize jsHandler=_jsHandler;
@property(retain, nonatomic) WSTemplateLogicController *logicController; // @synthesize logicController=_logicController;
@property(retain, nonatomic) FTSWebSearchPardusWebReportItem *reportItem; // @synthesize reportItem=_reportItem;
@property(nonatomic) __weak MMUIViewController *contentVC; // @synthesize contentVC=_contentVC;
@property(nonatomic) __weak id <FTSWebSearchPardusWebHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)pardusWebView_ActionClickNeedReport:(unsigned int)arg1 pos:(unsigned int)arg2 info:(id)arg3;
- (void)pardusWebView_StartWebSearch:(id)arg1;
- (void)pardusWebView_DidTerminate;
- (void)pardusWebView_WebViewReady:(id)arg1;
- (void)pardusWebView_RenderFinish:(id)arg1;
- (void)updatePardusData:(id)arg1 query:(id)arg2;
- (_Bool)isPardusViewReady;
- (id)getPardusTemplatePath;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

