//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary;

@protocol FTSWebSearchPardusWebHeaderViewDelegate <NSObject>
- (void)pardusWebView_didTerminate;
- (void)pardusWebView_actionClickNeedReport:(unsigned int)arg1 pos:(unsigned int)arg2 info:(NSDictionary *)arg3;
- (void)pardusWebView_startWebSearch:(NSDictionary *)arg1;
- (void)pardusWebView_renderFinish:(NSDictionary *)arg1;
- (void)pardusWebView_webViewReady:(NSDictionary *)arg1;
@end

