//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class LocalPackageInfo, RequestPackageInfo;

@interface GetDownloadUrlReqItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int appVersion; // @dynamic appVersion;
@property(nonatomic) unsigned int devUin; // @dynamic devUin;
@property(retain, nonatomic) LocalPackageInfo *localPackageInfo; // @dynamic localPackageInfo;
@property(nonatomic) _Bool needLatestVersion; // @dynamic needLatestVersion;
@property(nonatomic) _Bool needZstd; // @dynamic needZstd;
@property(retain, nonatomic) RequestPackageInfo *reqPackageInfo; // @dynamic reqPackageInfo;
@property(nonatomic) unsigned int supportedEncryptVersion; // @dynamic supportedEncryptVersion;

@end

