//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageTwoInputFilter.h"

@interface GPUImageVideoCombinationFilter : GPUImageTwoInputFilter
{
    int smoothDegreeUniform;
    int showCounterUniform;
    int showModeUniform;
    int brightnessUniform;
    int texelWidthUniform;
    int texelHeightUniform;
    int sharpnessUniform;
    int imageWidthFactorUniform;
    int imageHeightFactorUniform;
    int contrastUniform;
    int redUniform;
}

- (void)setupCombineFilterForSize:(struct CGSize)arg1;
- (void)setSharpness:(double)arg1;
- (void)setTexelHeight:(double)arg1;
- (void)setTexelWidth:(double)arg1;
- (void)setRed:(double)arg1;
- (void)setContrast:(double)arg1;
- (void)setBrightness:(double)arg1;
- (void)setShowMode:(int)arg1;
- (void)setRegionShow:(int)arg1;
- (void)setIntensity:(double)arg1;
- (id)init;

@end

