//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

@class GPUImageBilateralFilter, GPUImageBilateralSapatialCombineDenosing, GPUImageBuffer, GPUImageMotionCheck, GPUImageSpatialRecursiveDenosing, GPUImageStrongBilateralFilter, GPUImageVideoEnhancementFilter;

@interface GPUImageSpatiotemporalDenosing : GPUImageFilterGroup
{
    GPUImageBilateralFilter *bilateralFilter;
    GPUImageBilateralSapatialCombineDenosing *bilateralSapatialCombineDenosing;
    GPUImageSpatialRecursiveDenosing *spatialRecursiveDenosing;
    GPUImageMotionCheck *motionCheck;
    GPUImageBuffer *bufferFilter;
    GPUImageVideoEnhancementFilter *videoEnhancementFilter;
    GPUImageStrongBilateralFilter *strongBilateralFilter;
}

- (void).cxx_destruct;
- (void)setTemporalDenosingSwitch:(int)arg1;
- (void)setNoiseLevel:(float)arg1;
- (void)setTemporalDenosingLevel:(int)arg1;
- (void)setBilateralSapatialFilterControl:(int)arg1;
- (void)setSpatialRecursiveFilterControl:(int)arg1;
- (void)setMotionCheckControl:(int)arg1;
- (id)init;

@end

