//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSError, NSString, TPPlayerLayerViewContainer, TPPlayerVideo, UIImage;

@protocol ITPAVPlayer <NSObject>
@property(nonatomic) long long currentClipIndex;
@property(nonatomic) _Bool usesExternalPlaybackWhileExternalScreenIsActive;
@property(nonatomic) _Bool allowsExternalPlayback;
@property(copy, nonatomic) NSString *externalPlaybackVideoGravity;
@property(copy, nonatomic) NSString *videoGravity;
@property(nonatomic) _Bool enableResourceLoader;
@property(nonatomic) _Bool enableSnapshot;
@property(nonatomic) long long loopbackSkipEndPos;
@property(nonatomic) long long loopbackStartPos;
@property(nonatomic) _Bool enableLoopback;
@property(nonatomic) _Bool enableVideoFrameOutput;
@property(nonatomic) _Bool enableAccurateStartPos;
@property(readonly, nonatomic) int playerID;
@property(readonly, nonatomic) NSError *error;
@property long long playbackState;
@property(nonatomic) float volume;
@property(nonatomic) float rate;
@property(nonatomic) long long bufferedDuration;
@property(nonatomic) _Bool isCaching;
@property(nonatomic) double currentTimeBase;
@property(nonatomic) long long currentTime;
@property(nonatomic) long long duration;
@property(readonly, nonatomic) TPPlayerVideo *currentVideo;
@property __weak id delegate;
@property(retain, nonatomic) TPPlayerLayerViewContainer *view;
- (_Bool)deselectTrackInfoWithoutCallback:(long long)arg1 opaque:(long long)arg2;
- (_Bool)deselectTrackInfo:(long long)arg1 opaque:(long long)arg2;
- (_Bool)selectTrackInfo:(long long)arg1 opaque:(long long)arg2;
- (NSArray *)trackInfoArray;
- (void)setTimeObserverBlock:(void (^)(struct))arg1;
- (void)resumeOutputFrame;
- (void)pauseOutputFrame;
- (void)stopOutputFrame;
- (void)startOutputFrame:(double)arg1;
- (UIImage *)snapshot;
- (void)seekToTime:(long long)arg1;
- (void)stop;
- (void)pause;
- (void)play;
- (void)updateVideo:(TPPlayerVideo *)arg1;
- (void)loadVideo:(TPPlayerVideo *)arg1;
@end

