//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, TPDownloadParamData;
@protocol TPPreloadProxyDelegate;

@protocol ITPPreloadProxy <NSObject>
@property(nonatomic) __weak id <TPPreloadProxyDelegate> delegate;
- (NSString *)errorCodeStringWithPreloadId:(int)arg1;
- (_Bool)isAvailable;
- (void)pushEvent:(long long)arg1;
- (void)stopPreloadWithPreloadId:(int)arg1;
- (int)startClipPreloadWithFileId:(NSString *)arg1 downloadParamList:(NSArray *)arg2;
- (int)startPreloadWithFileId:(NSString *)arg1 downloadParam:(TPDownloadParamData *)arg2;
@end

