//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AVAsset, NSString, TPAudioFrameBuffer, TPSubtitleData, TPVideoFrameBuffer, UIImage;
@protocol ITPPlayer;

@protocol ITPPlayerDelegate <NSObject>
- (void)onPlayer:(id <ITPPlayer>)arg1 errorType:(long long)arg2 errorCode:(long long)arg3 arg1:(long long)arg4 arg2:(long long)arg5;
- (void)onCompletion:(id <ITPPlayer>)arg1;
- (void)onPrepared:(id <ITPPlayer>)arg1;

@optional
- (void)onPlayer:(id <ITPPlayer>)arg1 pictureInPictureErrorDidOccur:(long long)arg2;
- (void)onPlayer:(id <ITPPlayer>)arg1 pictureInPictureStateDidChange:(long long)arg2;
- (void)onPlayer:(id <ITPPlayer>)arg1 airplayErrorDidOccur:(long long)arg2;
- (void)onPlayer:(id <ITPPlayer>)arg1 airplayDidActive:(_Bool)arg2;
- (AVAsset *)onPlayer:(id <ITPPlayer>)arg1 assembleAVAssetWithUrl:(NSString *)arg2 atIndex:(unsigned long long)arg3;
- (void)onPlayer:(id <ITPPlayer>)arg1 audioFrameOut:(TPAudioFrameBuffer *)arg2;
- (void)onPlayer:(id <ITPPlayer>)arg1 videoFrameOut:(TPVideoFrameBuffer *)arg2;
- (void)onPlayer:(id <ITPPlayer>)arg1 captureVideoFailed:(long long)arg2;
- (void)onPlayer:(id <ITPPlayer>)arg1 captureVideoSuccess:(UIImage *)arg2;
- (void)onPlayer:(id <ITPPlayer>)arg1 subtitleData:(TPSubtitleData *)arg2;
- (void)onVideoSizeChanged:(id <ITPPlayer>)arg1 width:(int)arg2 height:(int)arg3;
- (void)onSeekComplete:(id <ITPPlayer>)arg1;
- (void)onPlayer:(id <ITPPlayer>)arg1 info:(unsigned long long)arg2 extra1:(long long)arg3 extra2:(long long)arg4 extraObject:(id)arg5;
@end

