//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol IWCTimeLineViewControllerExt <NSObject>
- (void)onTimeLineViewJumpToUnreadItem:(NSString *)arg1;
- (void)onTimeLineViewJumpToUnreadItemFail;
- (void)onTimeLineViewExposureFeedId:(NSString *)arg1;
- (void)onTimeLineViewWillAppearFeedId:(NSString *)arg1;
- (void)onTimeLineViewReturn;
- (void)onTimeLineViewDealloc;
- (void)onTimeLineViewMissReadJumpBtnClick:(unsigned int)arg1;
@end

