//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KvReportBaseItem.h"

@interface KvReportItem19285 : KvReportBaseItem
{
    unsigned int _scene_21;
    unsigned int _occasion_22;
    long long _imgSize_23;
}

@property(nonatomic) long long imgSize_23; // @synthesize imgSize_23=_imgSize_23;
@property(nonatomic) unsigned int occasion_22; // @synthesize occasion_22=_occasion_22;
@property(nonatomic) unsigned int scene_21; // @synthesize scene_21=_scene_21;
- (id)reportOrderedFieldNameArr;
- (unsigned int)reportKvId;

@end

