//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCPayLQTDepositManagePlanCgiDelegate-Protocol.h"

@class NSString;
@protocol LQTDepositPlanDeleteDelegate;

@interface LQTDepositPlanDelete : NSObject <WCPayLQTDepositManagePlanCgiDelegate>
{
    id <LQTDepositPlanDeleteDelegate> _delegate;
}

@property __weak id <LQTDepositPlanDeleteDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onWCPayLQTDepositManagePlanCgiError:(id)arg1 errorCode:(unsigned int)arg2;
- (void)onWCPayLQTDepositManagePlanCgiResponseOK:(id)arg1;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

