//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSMutableArray, NSString;

@interface MMFolder : NSObject <PBCoding>
{
    _Bool bFoundCache;
    int _level;
    NSString *name;
    long long size;
    NSMutableArray *subFiles;
    NSMutableArray *subFolders;
    long long diffCacheSize;
}

+ (void)initialize;
+ (void)PBArrayAdd_bFoundCache;
+ (void)PBArrayAdd_diffCacheSize;
+ (void)PBArrayAdd_subFolders;
+ (void)PBArrayAdd_subFiles;
+ (void)PBArrayAdd_size;
+ (void)PBArrayAdd_name;
@property int level; // @synthesize level=_level;
@property _Bool bFoundCache; // @synthesize bFoundCache;
@property long long diffCacheSize; // @synthesize diffCacheSize;
@property(retain) NSMutableArray *subFolders; // @synthesize subFolders;
@property(retain) NSMutableArray *subFiles; // @synthesize subFiles;
@property long long size; // @synthesize size;
@property(retain) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

