//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MMPageSheetProvider-Protocol.h"

@class MMPageSheetConfig, MMPageSheetProviderController, NSString, UIView, UIViewController;

@interface MMPageSheetAdapter : NSObject <MMPageSheetProvider>
{
    MMPageSheetConfig *_pageSheetConfig;
    UIView *_hostView;
    UIViewController *_hostViewController;
    double _contentHeight;
    MMPageSheetProviderController *_providerController;
}

+ (id)adatperWithView:(id)arg1 height:(double)arg2;
+ (id)adapterWithViewController:(id)arg1 height:(double)arg2;
@property(retain, nonatomic) MMPageSheetProviderController *providerController; // @synthesize providerController=_providerController;
@property(nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
@property(retain, nonatomic) UIViewController *hostViewController; // @synthesize hostViewController=_hostViewController;
@property(retain, nonatomic) UIView *hostView; // @synthesize hostView=_hostView;
- (void).cxx_destruct;
@property(retain, nonatomic) MMPageSheetConfig *pageSheetConfig; // @synthesize pageSheetConfig=_pageSheetConfig;
- (id)pageSheetProviderController;
- (void)didPushSelfInPage:(id)arg1;
- (double)pageSheetContentHeight;
- (id)pageSheetContentView;
- (void)popPageSheet;
- (void)pushPageSheet:(id)arg1;
- (void)dismissWithAnimated:(_Bool)arg1;
- (void)showWithAnimated:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

