//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MMPageSheetProvider-Protocol.h"

@class MMPageSheetConfig, MMPageSheetProviderController, NSString;

@interface MMPageSheetBaseView : UIView <MMPageSheetProvider>
{
    MMPageSheetConfig *_pageSheetConfig;
    MMPageSheetProviderController *_adapter;
    UIView *_detailView;
}

@property(retain, nonatomic) UIView *detailView; // @synthesize detailView=_detailView;
@property(nonatomic) __weak MMPageSheetProviderController *adapter; // @synthesize adapter=_adapter;
@property(retain, nonatomic) MMPageSheetConfig *pageSheetConfig; // @synthesize pageSheetConfig=_pageSheetConfig;
- (void).cxx_destruct;
- (void)popPageSheet;
- (void)pushPageSheet:(id)arg1;
- (void)dismissWithAnimated:(_Bool)arg1;
- (void)showWithAnimated:(_Bool)arg1;
- (id)pageSheetProviderController;
- (void)didPushSelfInPage:(id)arg1;
- (double)pageSheetContentHeight;
- (id)pageSheetContentView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

