//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIButton, UIColor, UIImage;
@protocol MMPageSheetBottomViewDelegate, MMPageSheetConfigDelegate;

@interface MMPageSheetConfig : NSObject
{
    _Bool _isAllowTapBackgroundToClose;
    _Bool _showCloseButton;
    _Bool _isConfirmButtonDisable;
    UIColor *_backgroundColor;
    NSString *_title;
    NSString *_subTitle;
    UIImage *_headIconImage;
    UIButton *_navLeftButton;
    UIButton *_navRightButton;
    long long _bottomType;
    id <MMPageSheetBottomViewDelegate> _bottomViewDelegate;
    id <MMPageSheetConfigDelegate> _delegate;
}

@property(nonatomic) __weak id <MMPageSheetConfigDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isConfirmButtonDisable; // @synthesize isConfirmButtonDisable=_isConfirmButtonDisable;
@property(nonatomic) __weak id <MMPageSheetBottomViewDelegate> bottomViewDelegate; // @synthesize bottomViewDelegate=_bottomViewDelegate;
@property(nonatomic) long long bottomType; // @synthesize bottomType=_bottomType;
@property(retain, nonatomic) UIButton *navRightButton; // @synthesize navRightButton=_navRightButton;
@property(retain, nonatomic) UIButton *navLeftButton; // @synthesize navLeftButton=_navLeftButton;
@property(nonatomic) _Bool showCloseButton; // @synthesize showCloseButton=_showCloseButton;
@property(retain, nonatomic) UIImage *headIconImage; // @synthesize headIconImage=_headIconImage;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) _Bool isAllowTapBackgroundToClose; // @synthesize isAllowTapBackgroundToClose=_isAllowTapBackgroundToClose;
- (void).cxx_destruct;
- (double)footerHeight;
- (_Bool)shouldShowFooter;
- (double)headerHeight:(_Bool)arg1;
- (_Bool)shouldShowHeader:(_Bool)arg1;

@end

