//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSIndexPath, UITableView, UITableViewCell, UIView;

@protocol MMTableViewReorderDelegate <NSObject>
- (_Bool)tableView:(UITableView *)arg1 reorderFromIndex:(NSIndexPath *)arg2 toIndex:(NSIndexPath *)arg3;

@optional
- (void)onReorderEnd;
- (UIView *)tableView:(UITableView *)arg1 draggingViewForIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldStartResortAtPos:(struct CGPoint)arg2 inCell:(UITableViewCell *)arg3 atIndexPath:(NSIndexPath *)arg4;
@end

