//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MMUILabel, MMWebImageView, UIButton, UIImageView, UIView;
@protocol MMToolManageTableViewCellDelegate;

@interface MMToolManageTableViewCell : UITableViewCell
{
    _Bool _isAdded;
    id <MMToolManageTableViewCellDelegate> _delegate;
    UIView *_bottomView;
    UIButton *_editButton;
    UIImageView *_reorderButton;
    MMWebImageView *_iconImageView;
    MMUILabel *_nameLabel;
}

@property(nonatomic) _Bool isAdded; // @synthesize isAdded=_isAdded;
@property(retain, nonatomic) MMUILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) MMWebImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIImageView *reorderButton; // @synthesize reorderButton=_reorderButton;
@property(retain, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak id <MMToolManageTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)isTouchAtResortButton:(struct CGPoint)arg1;
- (void)configueCell:(id)arg1 isAdded:(_Bool)arg2;
- (void)onClickEdit;
- (void)layoutSubviews;
- (void)initView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

