//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMVideCompressScanner : NSObject
{
    _Bool _m_isScanning;
    _Bool _m_isCanScan;
    int _m_scanTimes;
}

+ (id)sharedInstance;
@property int m_scanTimes; // @synthesize m_scanTimes=_m_scanTimes;
@property _Bool m_isCanScan; // @synthesize m_isCanScan=_m_isCanScan;
@property _Bool m_isScanning; // @synthesize m_isScanning=_m_isScanning;
- (void)updateVideoPath:(id)arg1 type:(int)arg2 format:(int)arg3;
- (_Bool)scanPath:(id)arg1 withType:(int)arg2;
- (void)checkScanTimes;
- (_Bool)currentScanState;
- (void)disableScan;
- (void)enableScan;
- (id)init;

@end

