//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class MPCommentMsg, NSMutableArray, NSString;

@interface MPCommentBaseCellViewModel : MMObject
{
    double _viewHeight;
    NSMutableArray *_contentLabelStyles;
    struct CGSize _contentLabelSize;
    _Bool _isLastItem;
    _Bool _isSelected;
    _Bool _isLike;
    unsigned int _likeCount;
    MPCommentMsg *_commentMsg;
    double _viewWidth;
    NSString *_content;
    double _headerMargin;
}

@property(readonly, nonatomic) double headerMargin; // @synthesize headerMargin=_headerMargin;
@property(readonly, nonatomic) unsigned int likeCount; // @synthesize likeCount=_likeCount;
@property(readonly, nonatomic) _Bool isLike; // @synthesize isLike=_isLike;
@property(readonly, nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(readonly, copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) _Bool isLastItem; // @synthesize isLastItem=_isLastItem;
@property(nonatomic) double viewWidth; // @synthesize viewWidth=_viewWidth;
@property(retain, nonatomic) MPCommentMsg *commentMsg; // @synthesize commentMsg=_commentMsg;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *headImageUrl;
@property(readonly, copy, nonatomic) NSString *nickname;
- (void)switchThumbsUpStatus;
- (void)clearLabelStyles;
- (id)cellViewClassName;
- (id)creatCommentCellView;
@property(readonly, nonatomic) double labelMaxWidth;
@property(readonly, nonatomic) NSMutableArray *contentLabelStyles;
@property(readonly, nonatomic) double replyContentHeight;
@property(readonly, nonatomic) double viewHeight;
- (id)initWithMPCommentMsg:(id)arg1;

@end

