//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface MPLandingPageReqExtInfo : MMObject
{
    unsigned long long _lastShowOversizeTimeStamp;
    unsigned long long _lastShowOversizeFileSize;
    unsigned long long _lastShowOversizeType;
}

@property(nonatomic) unsigned long long lastShowOversizeType; // @synthesize lastShowOversizeType=_lastShowOversizeType;
@property(nonatomic) unsigned long long lastShowOversizeFileSize; // @synthesize lastShowOversizeFileSize=_lastShowOversizeFileSize;
@property(nonatomic) unsigned long long lastShowOversizeTimeStamp; // @synthesize lastShowOversizeTimeStamp=_lastShowOversizeTimeStamp;

@end

