//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMTimerLabel, UIButton, UILabel;
@protocol MultitalkSecondOperateViewDelegate;

@interface MultitalkSecondOperateView : UIView
{
    id <MultitalkSecondOperateViewDelegate> _m_delegate;
    UIButton *_m_addMemberButton;
    UIButton *_m_minimizeButton;
    MMTimerLabel *_m_timerView;
    UILabel *_m_statusLabel;
}

@property(retain, nonatomic) UILabel *m_statusLabel; // @synthesize m_statusLabel=_m_statusLabel;
@property(retain, nonatomic) MMTimerLabel *m_timerView; // @synthesize m_timerView=_m_timerView;
@property(retain, nonatomic) UIButton *m_minimizeButton; // @synthesize m_minimizeButton=_m_minimizeButton;
@property(retain, nonatomic) UIButton *m_addMemberButton; // @synthesize m_addMemberButton=_m_addMemberButton;
@property(nonatomic) __weak id <MultitalkSecondOperateViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (long long)currentDuration;
- (void)restartTimer;
- (void)updateStatusWording:(id)arg1;
- (void)onMinimizeButtonClick;
- (void)onAddMemberButtonClick;
- (void)initStatusLabel;
- (void)initTimerView;
- (void)initAddMemberButton;
- (void)initMinimizeButton;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateMinimizeButtonHidden:(_Bool)arg1;
- (void)updateAddMemberButtonHidden:(_Bool)arg1;
- (void)updateAddMemberEnabled:(_Bool)arg1;
- (void)showOperateView;
- (void)hideOperateView;

@end

