//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WCVideoRender;

@interface MultiTalkContactsBigCellView : UIView
{
    WCVideoRender *_render;
}

@property(retain, nonatomic) WCVideoRender *render; // @synthesize render=_render;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithRender:(id)arg1;

@end

