//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSHTTPURLResponse.h>

@interface NSHTTPURLResponse (Extend)
- (id)mm_contentDispositionFileExtensionName;
- (id)mm_contentDispositionFileName;
- (_Bool)mm_isContentDispositionAttachment;
- (id)mm_contentDispositionType;
- (unsigned long long)mm_contentLength;
- (id)mm_contentTypeIfHasPrefixApplication;
@end

