//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTColumnCoding-Protocol.h"

@interface NSObject (MethodSwizzlingCategoryWeChat) <WCTColumnCoding>
+ (void)switchSomeCriticalMethod;
+ (id)tp_modelWithDictionary:(id)arg1;
+ (id)tp_modelWithJSON:(id)arg1;
+ (id)_yy_dictionaryWithJSON:(id)arg1;
+ (id)event_logging_alloc;
+ (int)columnType;
+ (id)unarchiveWithWCTValue:(id)arg1;
+ (_Bool)swizzleClassMethod:(SEL)arg1 withImp:(CDUnknownFunctionPointerType)arg2 store:(CDUnknownFunctionPointerType *)arg3;
+ (_Bool)swizzleClassMethod:(SEL)arg1 withClassMethod:(SEL)arg2;
+ (_Bool)swizzleMethod:(SEL)arg1 withImp:(CDUnknownFunctionPointerType)arg2 store:(CDUnknownFunctionPointerType *)arg3;
+ (_Bool)swizzleMethod:(SEL)arg1 withMethod:(SEL)arg2;
+ (void)safeCancelPreviousPerformRequestsWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;
+ (void)safeCancelPreviousPerformRequestsWithTarget:(id)arg1;
+ (void)WCAop_removeBlockOfSelector:(SEL)arg1 atPosition:(unsigned long long)arg2 withTag:(id)arg3;
+ (unsigned long long)WCAop_hookSelector:(SEL)arg1 atPosition:(unsigned long long)arg2 withTag:(id)arg3 usingBlock:(id)arg4;
+ (id)yy_modelWithXmlReaderNode:(struct XmlReaderNode_t *)arg1;
+ (id)yy_modelWithXmlString:(id)arg1 RootTag:(id)arg2;
+ (id)yy_modelWithDictionary:(id)arg1;
+ (id)yy_modelWithJSON:(id)arg1;
+ (id)_yy_dictionaryWithJSON:(id)arg1;
+ (id)yy_modelWithXML:(id)arg1 xmlTag:(id)arg2;
- (id)valueForUndefinedKey:(id)arg1;
- (id)tp_modelDescription;
- (_Bool)tp_modelIsEqual:(id)arg1;
- (unsigned long long)tp_modelHash;
- (id)tp_modelInitWithCoder:(id)arg1;
- (void)tp_modelEncodeWithCoder:(id)arg1;
- (id)tp_modelCopy;
- (id)tp_modelToJSONString;
- (id)tp_modelToJSONData;
- (id)tp_modelToJSONObject;
- (_Bool)tp_modelSetWithDictionary:(id)arg1;
- (_Bool)tp_modelSetWithJSON:(id)arg1;
- (void)performWithAsyncTrace:(id)arg1;
- (void)hookPerformSelector:(SEL)arg1 onThread:(id)arg2 withObject:(id)arg3 waitUntilDone:(_Bool)arg4 modes:(id)arg5;
- (id)archivedWCTValue;
- (id)clsptr;
- (id)pop_animationForKey:(id)arg1;
- (id)pop_animationKeys;
- (void)pop_removeAnimationForKey:(id)arg1;
- (void)pop_removeAllAnimations;
- (void)pop_addAnimation:(id)arg1 forKey:(id)arg2;
- (void)safePerformSelector:(SEL)arg1 withObject:(id)arg2 afterDelay:(double)arg3;
- (void)WCAop_removeBlockOfSelector:(SEL)arg1 atPosition:(unsigned long long)arg2 withTag:(id)arg3;
- (unsigned long long)WCAop_hookSelector:(SEL)arg1 atPosition:(unsigned long long)arg2 withTag:(id)arg3 usingBlock:(id)arg4;
- (id)yy_modelToXmlStringWithRootTag:(id)arg1;
- (void)yy_modelSetWithXmlReaderNode:(struct XmlReaderNode_t *)arg1;
- (_Bool)yy_modelSetWithXmlString:(id)arg1 RootTag:(id)arg2;
- (id)yy_modelDescription;
- (_Bool)yy_modelIsEqual:(id)arg1;
- (unsigned long long)yy_modelHash;
- (id)yy_modelInitWithCoder:(id)arg1;
- (void)yy_modelEncodeWithCoder:(id)arg1;
- (id)yy_modelCopy;
- (id)yy_modelToJSONString;
- (id)yy_modelToJSONData;
- (id)yy_modelToJSONObject;
- (_Bool)yy_modelSetWithDictionary:(id)arg1;
- (_Bool)yy_modelSetWithJSON:(id)arg1;
- (void)removeAssociatedObjects;
- (void)detachObjectForKey:(id)arg1;
- (id)getAttachedObjectForKey:(id)arg1;
- (void)attachObject:(id)arg1 forKey:(id)arg2;
- (const void *)computeKeyFromString:(id)arg1;
- (id)JSONRepresentation;
- (id)yy_modelToXMLWithXmlTag:(id)arg1 lowercaseMode:(_Bool)arg2;
- (id)yy_modelToXMLWithXmlTag:(id)arg1;
@end

