//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IAudioSenderExt-Protocol.h"
#import "InputControllerDelegate-Protocol.h"

@class AudioRecorderUserData, CADisplayLink, MMGrowTextView, MMNewVoiceInputReportObj, MMTimer, NSMutableArray, NSString, UIButton, UILabel, WCInputController, WCRecordFeedbackView;
@protocol RecordInfoContentViewDelegate;

@interface RecordInfoContentView : UIView <IAudioSenderExt, InputControllerDelegate>
{
    _Bool _bIsForceEndTrans;
    _Bool _needShowCountDown;
    _Bool _bTransStartSucc;
    _Bool _bCanStartTextViewAnimation;
    unsigned int _localId;
    unsigned int _inputLanguageType;
    unsigned int _translatingWordingIndex;
    NSString *_chatName;
    UIView *_operatePanelView;
    UIView *_arrowIconView;
    MMNewVoiceInputReportObj *_reportObj;
    unsigned long long _recordState;
    AudioRecorderUserData *_recordInfo;
    id <RecordInfoContentViewDelegate> _delegate;
    unsigned long long _transState;
    NSMutableArray *_arrVoiceIds;
    UIView *_bottomView;
    UIView *_contentView;
    MMGrowTextView *_transTextView;
    WCInputController *_inputController;
    WCRecordFeedbackView *_feedbackView;
    UILabel *_countdownLabel;
    UIButton *_errorButton;
    double _currentLength;
    CADisplayLink *_widthGrowDisplayLink;
    MMTimer *_translatingTimer;
    NSString *_translatedText;
    NSString *_translatingWording;
}

@property(nonatomic) _Bool bCanStartTextViewAnimation; // @synthesize bCanStartTextViewAnimation=_bCanStartTextViewAnimation;
@property(nonatomic) _Bool bTransStartSucc; // @synthesize bTransStartSucc=_bTransStartSucc;
@property(nonatomic) unsigned int translatingWordingIndex; // @synthesize translatingWordingIndex=_translatingWordingIndex;
@property(retain, nonatomic) NSString *translatingWording; // @synthesize translatingWording=_translatingWording;
@property(retain, nonatomic) NSString *translatedText; // @synthesize translatedText=_translatedText;
@property(retain, nonatomic) MMTimer *translatingTimer; // @synthesize translatingTimer=_translatingTimer;
@property(retain, nonatomic) CADisplayLink *widthGrowDisplayLink; // @synthesize widthGrowDisplayLink=_widthGrowDisplayLink;
@property(nonatomic) double currentLength; // @synthesize currentLength=_currentLength;
@property(retain, nonatomic) UIButton *errorButton; // @synthesize errorButton=_errorButton;
@property(retain, nonatomic) UILabel *countdownLabel; // @synthesize countdownLabel=_countdownLabel;
@property(nonatomic) _Bool needShowCountDown; // @synthesize needShowCountDown=_needShowCountDown;
@property(retain, nonatomic) WCRecordFeedbackView *feedbackView; // @synthesize feedbackView=_feedbackView;
@property(retain, nonatomic) WCInputController *inputController; // @synthesize inputController=_inputController;
@property(retain, nonatomic) MMGrowTextView *transTextView; // @synthesize transTextView=_transTextView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) _Bool bIsForceEndTrans; // @synthesize bIsForceEndTrans=_bIsForceEndTrans;
@property(retain, nonatomic) NSMutableArray *arrVoiceIds; // @synthesize arrVoiceIds=_arrVoiceIds;
@property(nonatomic) unsigned long long transState; // @synthesize transState=_transState;
@property(nonatomic) __weak id <RecordInfoContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AudioRecorderUserData *recordInfo; // @synthesize recordInfo=_recordInfo;
@property(nonatomic) unsigned int inputLanguageType; // @synthesize inputLanguageType=_inputLanguageType;
@property(nonatomic) unsigned long long recordState; // @synthesize recordState=_recordState;
@property(retain, nonatomic) MMNewVoiceInputReportObj *reportObj; // @synthesize reportObj=_reportObj;
@property(retain, nonatomic) UIView *arrowIconView; // @synthesize arrowIconView=_arrowIconView;
@property(nonatomic) __weak UIView *operatePanelView; // @synthesize operatePanelView=_operatePanelView;
@property(nonatomic) unsigned int localId; // @synthesize localId=_localId;
@property(retain, nonatomic) NSString *chatName; // @synthesize chatName=_chatName;
- (void).cxx_destruct;
- (void)keyboardWillShow;
- (double)getVisibleHeight;
- (void)didCommitText:(id)arg1;
- (void)textViewTextDidChange;
- (void)MMGrowTextViewBeginEditing:(id)arg1;
- (void)OnRecordVoiceChangeWithUserData:(id)arg1;
- (void)OnVoiceTransResultChange:(id)arg1 InputId:(unsigned int)arg2;
- (void)OnVoiceTransTimeout:(unsigned int)arg1;
- (void)OnVoiceTransEnd:(unsigned int)arg1 VoiceIds:(id)arg2;
- (id)generateAttrTextFrom:(id)arg1 withUncertainLength:(unsigned int)arg2 andTranslatingWording:(id)arg3;
- (void)displayTranslateResultText;
- (unsigned int)getUncertainLength;
- (unsigned int)getSuffixDotCountWithString:(id)arg1;
- (void)updateTranslatingWording:(_Bool)arg1;
- (void)checkChangeTranslatingWording;
- (void)makeTranslateStopWithError:(id)arg1;
- (void)pauseTranslate;
- (void)startTranslate;
- (void)invalidateTranslateTimer;
- (void)changeRecordStateTo:(unsigned long long)arg1 CenterX:(double)arg2;
- (id)getTransResult;
- (void)onGrowWidthDisplayLinkCallback;
- (void)startWidthGrowDisplayLink;
- (void)removeWidthGrowDisplayLink;
- (void)setErrorMessage:(id)arg1;
- (void)setTimeoutCountDown:(long long)arg1 needShow:(_Bool)arg2;
- (void)setBubbleBackgroundColor:(id)arg1;
- (void)setPeakPower:(float)arg1;
- (void)updateSubviews;
- (void)adjustTextMaxSize;
- (void)resizeTextView;
- (void)updateFeedbackViewWithRecordState:(unsigned long long)arg1;
- (void)updateCountDownLabelAndFeedbackViewWithRecordState:(unsigned long long)arg1;
- (void)removeFeedbackView;
- (id)createTransTextView;
- (void)dealloc;
- (id)initWithBottomView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

