//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ImageSelectorController, NSMutableArray, UIViewController;

@protocol SelectorControllerDelegate <NSObject>
- (_Bool)showAddView;
- (UIViewController *)getViewController;

@optional
- (void)ImageSelectorController:(ImageSelectorController *)arg1 didDeleteImageAtIndex:(unsigned long long)arg2;
- (void)onImageOrderChange;
- (void)onRemindContactSelected:(NSMutableArray *)arg1;
- (_Bool)shouldJustReturnMMAsset;
- (void)imagesUpdated;
- (void)hideInputController;
- (void)updateSelectorView;
@end

