//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SolitaireConfig : NSObject
{
    _Bool _isOpenEntry;
    _Bool _isOpenAnalysis;
    unsigned int _lastupTime;
}

@property(nonatomic) unsigned int lastupTime; // @synthesize lastupTime=_lastupTime;
@property(nonatomic) _Bool isOpenAnalysis; // @synthesize isOpenAnalysis=_isOpenAnalysis;
@property(nonatomic) _Bool isOpenEntry; // @synthesize isOpenEntry=_isOpenEntry;
- (_Bool)isSolitaireOpenAnalysis;
- (_Bool)isSolitaireOpenEntry;
- (void)checkUPTime;
- (void)resetConfig;
- (id)init;

@end

