//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SolitaireBadCaseProcessor : NSObject
{
}

+ (_Bool)isItemCreatedFromNotBelongSelf:(id)arg1 Solitaire:(id)arg2;
+ (id)getNakedContent:(id)arg1;
+ (_Bool)checkIfNeedDropLocalExistSolitaire:(id)arg1 InfoObj:(id)arg2;
+ (void)separateMultiItemEditInOneLineWithInfo:(id)arg1 Obj:(id)arg2;
+ (_Bool)isHitMultiSolitaire:(id)arg1;

@end

