//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TencentIndoorRoadFileManager : NSObject
{
    NSString *_roadRootPath;
    NSString *_destPath;
}

+ (id)sharedInstance;
@property(copy) NSString *destPath; // @synthesize destPath=_destPath;
@property(copy, nonatomic) NSString *roadRootPath; // @synthesize roadRootPath=_roadRootPath;
- (void).cxx_destruct;
- (void)writeDataToFile:(id)arg1 filePath:(id)arg2;
- (void)deletOldVersionData:(id)arg1 curVersion:(int)arg2;
- (void)deletWithPath:(id)arg1;
- (_Bool)saveIndoorRoadData:(id)arg1 withBuildid:(id)arg2;
- (id)getUnzipFilePath;
- (id)getDataVersionWithBuildID:(id)arg1;
- (id)init;

@end

