//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TencentLBSLocation;

@interface TencentLBSBleLocController : NSObject
{
    TencentLBSLocation *_beaconLocation;
    TencentLBSLocation *_pdrLocation;
}

+ (id)sharedInstance;
@property(retain) TencentLBSLocation *pdrLocation; // @synthesize pdrLocation=_pdrLocation;
@property(retain) TencentLBSLocation *beaconLocation; // @synthesize beaconLocation=_beaconLocation;
- (void).cxx_destruct;
- (id)getTencentPdrLocation;
- (void)updatePdrLocation:(id)arg1;
- (id)getTencentBleLocation;
- (void)updateBleLocation:(id)arg1;

@end

