//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TencentIndoorRoadManager : NSObject
{
    NSString *_curBuildid;
}

+ (id)sharedInstance;
@property(retain) NSString *curBuildid; // @synthesize curBuildid=_curBuildid;
- (void).cxx_destruct;
- (_Bool)downloadIndoorRoadDataWithBuildid:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)resetBuildid;

@end

