//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ReaderMessageCellView.h"

#import "ILinkEventExt-Protocol.h"
#import "RichTextLayoutDelegate-Protocol.h"

@class MMUIButton, NSString, RichTextView, TextReaderMessageViewModel, UIImageView, WAAppIdToUsernameTransfer;

@interface TextReaderMessageCellView : ReaderMessageCellView <RichTextLayoutDelegate, ILinkEventExt>
{
    UIImageView *m_bgImageView;
    RichTextView *m_titleView;
    MMUIButton *m_detailButton;
    WAAppIdToUsernameTransfer *m_appIdTransfer;
}

- (void).cxx_destruct;
- (void)onWeAppLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (struct CGRect)previewingSourceRectForLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (void)onBottomButtonClicked;
- (void)initDetailButton;
- (void)layoutContentView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) TextReaderMessageViewModel *viewModel;

@end

