//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TPAppleAudioRouteManagerImpl : NSObject
{
    struct set<ITPAudioRouteManagerCallback *, std::__1::less<ITPAudioRouteManagerCallback *>, std::__1::allocator<ITPAudioRouteManagerCallback *>> _callbacks;
    deque_30be1abd _currentRoutes;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onAudioSessionRouteChange:(id)arg1;
- (void)unRegisterObserver;
- (void)registerObserver;
- (void)initCurrentRoutes;
- (void)updateCurrentRoutesFromOutputs:(id)arg1;
- (int)getRouteTypeFromAVAudioSessionPort:(id)arg1;
- (_Bool)isRouteTypeOn:(int)arg1;
- (deque_30be1abd)getCurrentRoutes;
- (void)removeCallback:(struct ITPAudioRouteManagerCallback *)arg1;
- (void)addCallback:(struct ITPAudioRouteManagerCallback *)arg1;
- (void)dealloc;
- (id)init;

@end

