//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVMediaSelectionGroup, AVMediaSelectionOption;

@interface TPAVTrackInfo : NSObject
{
    _Bool _isSelected;
    AVMediaSelectionOption *_option;
    AVMediaSelectionGroup *_group;
}

@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) AVMediaSelectionGroup *group; // @synthesize group=_group;
@property(retain, nonatomic) AVMediaSelectionOption *option; // @synthesize option=_option;
- (void).cxx_destruct;

@end

