//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITPStrategy-Protocol.h"

@class NSArray, NSString, TPStrategyConfig;

@interface TPBaseStrategy : NSObject <ITPStrategy>
{
    TPStrategyConfig *_config;
    NSArray *_contextList;
}

+ (id)strategyWithConfig:(id)arg1;
@property(copy, nonatomic) NSArray *contextList; // @synthesize contextList=_contextList;
@property(retain, nonatomic) TPStrategyConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (_Bool)isPlayerTypeValidForCurrentPlayerScene;
- (id)defultPlayerTypeList;
- (void)addStrategyContext:(id)arg1;
- (long long)playerTypeForRetry:(id)arg1;
- (long long)playerTypeForOpen:(id)arg1;
- (id)lastContext;
- (_Bool)shouldRetry;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

