//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface TPBufferedRecord : NSObject
{
    _Bool _isBuffering;
    NSMutableArray *_bufferedStepArray;
}

@property(retain, nonatomic) NSMutableArray *bufferedStepArray; // @synthesize bufferedStepArray=_bufferedStepArray;
@property(nonatomic) _Bool isBuffering; // @synthesize isBuffering=_isBuffering;
- (void).cxx_destruct;

@end

