//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol TPDLProxyAdapterDelegate;

@interface TPDLProxyAdapterManager : NSObject
{
    id <TPDLProxyAdapterDelegate> mAdapter;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (long long)getCurrentFilesize:(int)arg1;
- (long long)getCurrentOffset:(int)arg1;
- (id)getProxyClipUrl:(int)arg1 withClipNo:(int)arg2 urlType:(int)arg3;
- (void)stopPlay:(int)arg1;
- (int)startOnlineOrOfflinePlay:(id)arg1 withDltype:(int)arg2 withCid:(id)arg3 withVid:(id)arg4 withFormat:(id)arg5 withIsCharge:(_Bool)arg6 withStartTime:(int)arg7 withEndTime:(int)arg8 withVinfoExtraInfo:(id)arg9 withExtraParams:(id)arg10;
- (id)getOfflineRecordVinfo:(id)arg1 withFormat:(id)arg2;
- (void)setAdapter:(id)arg1;
- (id)init;

@end

