//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol TPDLProxyLogDelegate <NSObject>
- (void)logDebug:(NSString *)arg1 line:(int)arg2 tag:(NSString *)arg3 msg:(NSString *)arg4;
- (void)logError:(NSString *)arg1 line:(int)arg2 tag:(NSString *)arg3 msg:(NSString *)arg4;
- (void)logWarn:(NSString *)arg1 line:(int)arg2 tag:(NSString *)arg3 msg:(NSString *)arg4;
- (void)logInfo:(NSString *)arg1 line:(int)arg2 tag:(NSString *)arg3 msg:(NSString *)arg4;
@end

