//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface TPDownloadProxy : NSObject
{
    int _serviceType;
    NSString *_currentStoragePath;
    NSMutableDictionary *_storageMap;
}

@property(retain, nonatomic) NSMutableDictionary *storageMap; // @synthesize storageMap=_storageMap;
@property(copy, nonatomic) NSString *currentStoragePath; // @synthesize currentStoragePath=_currentStoragePath;
@property(nonatomic) int serviceType; // @synthesize serviceType=_serviceType;
- (void).cxx_destruct;
- (void)setPlayer:(int)arg1 Resourceloader:(void *)arg2;
- (void)setPlayState:(int)arg1 state:(int)arg2;
- (void)setMaxStorageSizeMB:(long long)arg1;
- (void)updateStoragePath:(id)arg1;
- (int)removeOfflineDownload:(id)arg1;
- (int)stopOfflineDownload:(int)arg1;
- (void)startTask:(int)arg1;
- (int)startClipOfflineDownload:(id)arg1 clipCount:(int)arg2 delegate:(id)arg3;
- (int)startOfflineDownload:(id)arg1 downloadParam:(id)arg2 delegate:(id)arg3;
- (void)pushEvent:(long long)arg1;
- (void)setUserData:(id)arg1 value:(id)arg2;
- (void)stopPreload:(int)arg1;
- (int)startPreload:(id)arg1 downloadParam:(id)arg2 delegate:(id)arg3;
- (int)resumeDownload:(int)arg1;
- (int)pauseDownload:(int)arg1;
- (void)stopPlay:(int)arg1;
- (id)getPlayErrorCodeStr:(int)arg1;
- (id)getClipPlayUrl:(int)arg1 clipNo:(int)arg2;
- (id)getPlayUrl:(int)arg1 urlType:(int)arg2;
- (_Bool)setClipInfo:(int)arg1 clipNo:(int)arg2 clipFileId:(id)arg3 downloadParam:(id)arg4;
- (int)startClipPlay:(id)arg1 clipNo:(int)arg2 delegate:(id)arg3;
- (int)startPlay:(id)arg1 downloadParam:(id)arg2 delegate:(id)arg3;
- (void)setLogDelegate:(id)arg1;
- (int)deinit;
- (int)initDownloadProxy:(id)arg1;
- (id)initWithServiceType:(int)arg1;

@end

