//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol TPLogDelegate <NSObject>
- (void)logWithLevel:(int)arg1 tag:(NSString *)arg2 file:(const char *)arg3 function:(const char *)arg4 line:(unsigned long long)arg5 format:(NSString *)arg6 args:(char *)arg7;
@end

