//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TPLoopbackParams : NSObject
{
    _Bool _isLoopback;
    long long _startPositionMs;
    long long _endPositionMs;
}

+ (id)paramsWithIsLoopback:(_Bool)arg1 startPositionMs:(long long)arg2 endPositionMs:(long long)arg3;
@property(nonatomic) long long endPositionMs; // @synthesize endPositionMs=_endPositionMs;
@property(nonatomic) long long startPositionMs; // @synthesize startPositionMs=_startPositionMs;
@property(nonatomic) _Bool isLoopback; // @synthesize isLoopback=_isLoopback;

@end

