//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITPMediaAsset-Protocol.h"

@class NSArray, NSMutableArray, NSString;

@interface TPMediaTrack : NSObject <ITPMediaAsset>
{
    int _trackId;
    long long _mediaType;
    NSMutableArray *_clipArray;
}

+ (id)mediaTrackWithTrackMediaType:(long long)arg1;
+ (id)mediaTrackWithTrackId:(int)arg1 mediaType:(long long)arg2;
@property(retain, nonatomic) NSMutableArray *clipArray; // @synthesize clipArray=_clipArray;
@property(nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
@property(nonatomic) int trackId; // @synthesize trackId=_trackId;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *url;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) CDStruct_1b6d18a9 totalDurationMs;
@property(readonly, nonatomic) NSArray *allTrakClips;
- (id)trackClipWithId:(int)arg1;
- (void)removeAllTrackClips;
- (_Bool)removeTrackClip:(id)arg1;
- (_Bool)insertTrackClip:(id)arg1 afterClipId:(int)arg2;
- (_Bool)addTrackClip:(id)arg1;
- (id)initWithTrackId:(int)arg1 mediaType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

