//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITPMediaAsset-Protocol.h"

@class NSString, NSURL;

@interface TPMediaClip : NSObject <ITPMediaAsset>
{
    int _clipId;
    long long _mediaType;
    NSURL *_filePath;
    CDStruct_e83c9415 _timeRange;
}

+ (id)mediaTrackClipWithFilePath:(id)arg1 mediaType:(long long)arg2;
+ (int)genTrackClipIdWithMediaType:(long long)arg1;
@property(nonatomic) CDStruct_e83c9415 timeRange; // @synthesize timeRange=_timeRange;
@property(retain, nonatomic) NSURL *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
@property(nonatomic) int clipId; // @synthesize clipId=_clipId;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *url;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) CDStruct_1b6d18a9 duration;
- (id)initWithFilePath:(id)arg1 mediaType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

