//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TPOptionalParamQueueInt : NSObject
{
    unsigned long long _key;
    NSArray *_value;
}

@property(copy, nonatomic) NSArray *value; // @synthesize value=_value;
@property(nonatomic) unsigned long long key; // @synthesize key=_key;
- (void).cxx_destruct;

@end

