//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TPOptionalParamBool, TPOptionalParamLong, TPOptionalParamQueueInt, TPOptionalParamQueueString, TPOptionalParamString;

@interface TPOptionalParam : NSObject
{
    unsigned long long _paramType;
    TPOptionalParamLong *_paramLong;
    TPOptionalParamBool *_paramBool;
    TPOptionalParamString *_paramString;
    TPOptionalParamQueueInt *_paramQueueInt;
    TPOptionalParamQueueString *_paramQueueString;
}

+ (id)paramQueueStringWithKey:(unsigned long long)arg1 value:(id)arg2;
+ (id)paramQueueIntWithKey:(unsigned long long)arg1 value:(id)arg2;
+ (id)paramStringWithKey:(unsigned long long)arg1 value:(id)arg2 param1:(id)arg3 param2:(id)arg4;
+ (id)paramBoolWithKey:(unsigned long long)arg1 value:(_Bool)arg2 param1:(_Bool)arg3 param2:(_Bool)arg4;
+ (id)paramLongWithKey:(unsigned long long)arg1 value:(long long)arg2 param1:(long long)arg3 param2:(long long)arg4;
@property(retain, nonatomic) TPOptionalParamQueueString *paramQueueString; // @synthesize paramQueueString=_paramQueueString;
@property(retain, nonatomic) TPOptionalParamQueueInt *paramQueueInt; // @synthesize paramQueueInt=_paramQueueInt;
@property(retain, nonatomic) TPOptionalParamString *paramString; // @synthesize paramString=_paramString;
@property(retain, nonatomic) TPOptionalParamBool *paramBool; // @synthesize paramBool=_paramBool;
@property(retain, nonatomic) TPOptionalParamLong *paramLong; // @synthesize paramLong=_paramLong;
@property(nonatomic) unsigned long long paramType; // @synthesize paramType=_paramType;
- (void).cxx_destruct;
- (id)description;
- (id)queueStringValue;
- (id)queueIntValue;
- (id)stringValue;
- (_Bool)boolValue;
- (long long)longValue;
- (unsigned long long)key;
- (id)init;

@end

