//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TPParamUtils : NSObject
{
}

+ (void)setPlaybackInfo:(id)arg1 toPlayer:(id)arg2;
+ (void)setPlaybackParamsAfterPrepared:(id)arg1 toPlayer:(id)arg2;
+ (void)setPlaybackParams:(id)arg1 toPlayer:(id)arg2 withPlayerType:(long long)arg3;

@end

