//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TPThumbPlayerLogDelegate-Protocol.h"

@class NSString;

@interface TPPlayerMgr : NSObject <TPThumbPlayerLogDelegate>
{
    _Bool _initialized;
}

+ (id)sharedManager;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
- (void)logWithLevel:(long long)arg1 tag:(id)arg2 content:(id)arg3;
- (id)playerCoreVersion;
- (id)thumbPlayerVersion;
- (id)downloadProxyVersion;
- (void)setAppInfoWithAppVersion:(id)arg1 buildVerson:(id)arg2;
- (void)setUpcInfoWithUpc:(id)arg1 upcState:(long long)arg2;
- (void)setUserInfoWithUin:(id)arg1 isVip:(_Bool)arg2;
- (void)setProxyConfigWithPlatform:(long long)arg1 cacheDir:(id)arg2 dataDir:(id)arg3 configDir:(id)arg4;
- (void)setProxyEnable:(_Bool)arg1;
- (void)setProxyServiceType:(long long)arg1;
- (void)setLogDelegate:(id)arg1;
- (void)initSDKWithGuid:(id)arg1 platform:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

