//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITPPlayerAdapterHandler-Protocol.h"

@class NSString, TPPlayerAdapter;

@interface TPPlayerPictureInPictureHandler : NSObject <ITPPlayerAdapterHandler>
{
    TPPlayerAdapter *_adapter;
    long long _state;
    long long _prePlayerType;
}

+ (id)handlerForAdapter:(id)arg1;
@property(nonatomic) long long prePlayerType; // @synthesize prePlayerType=_prePlayerType;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic) __weak TPPlayerAdapter *adapter; // @synthesize adapter=_adapter;
- (void).cxx_destruct;
- (void)restoreFromPipWithError:(long long)arg1;
- (_Bool)handlePictureInPictureErrorDidOccur:(long long)arg1;
- (_Bool)handlePictureInPictureStateDidChange:(long long)arg1;
- (long long)handleStopPictureInPicture;
- (long long)handleStartPictureInPicture;
- (_Bool)handleStop;
- (_Bool)handleOnPrepared;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

