//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TPPlayerStateWrapper;

@interface TPPlayerStateStrategy : NSObject
{
    TPPlayerStateWrapper *_stateWrapper;
}

@property(retain, nonatomic) TPPlayerStateWrapper *stateWrapper; // @synthesize stateWrapper=_stateWrapper;
- (void).cxx_destruct;
- (_Bool)isValidStateToCallbackOnSeekComplete;
- (_Bool)isValidStateToCallbackOnDataOutput;
- (_Bool)isValidStateToCallbackOnVideoSizeChanged;
- (_Bool)isValidStateToCallbackOnError;
- (_Bool)isValidStateToCallbackOnInfo;
- (_Bool)isValidStateToCallbackOnComplete;
- (_Bool)isValidStateToCallbackOnPreared;
- (_Bool)isValidStateToCallRelease;
- (_Bool)isValidStateToCallGetBufferPercent;
- (_Bool)isValidStateToCallGetState;
- (_Bool)isValidStateToCallGetVideoSize;
- (_Bool)isValidStateToCallGetPosition;
- (_Bool)isValidStateToCallGetDuration;
- (_Bool)isValidStateToCallSelectProgram;
- (_Bool)isValidStateToCallDeselectTrack;
- (_Bool)isValidStateToCallSelectTrack;
- (_Bool)isValidStateToCallSwitchDefinition;
- (_Bool)isValidStateToCallSeek;
- (_Bool)isValidStateToCallReset;
- (_Bool)isValidStateToCallStop;
- (_Bool)isValidStateToCallPause;
- (_Bool)isValidStateToCallStart;
- (_Bool)isValidStateToCallSetView;
- (_Bool)isValidStateToCallSetParams;
- (_Bool)isValidStateToCallSetDataSource;
- (_Bool)isValidStateToCallPrepare;
- (_Bool)isValidStateToCallBack:(unsigned long long)arg1;
- (_Bool)isValidStateToCall:(unsigned long long)arg1;
- (id)initWithStateWrapper:(id)arg1;

@end

