//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TPUrlDataSource;
@protocol ITPMediaAsset;

@interface TPPlayerDataSource : NSObject
{
    TPUrlDataSource *_urlDataSource;
    id <ITPMediaAsset> _mediaAsset;
}

+ (id)dataSourceWithMediaAsset:(id)arg1;
+ (id)dataSourceWithUrlDataSource:(id)arg1;
@property(retain, nonatomic) id <ITPMediaAsset> mediaAsset; // @synthesize mediaAsset=_mediaAsset;
@property(retain, nonatomic) TPUrlDataSource *urlDataSource; // @synthesize urlDataSource=_urlDataSource;
- (void).cxx_destruct;
- (_Bool)isValid;

@end

