//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TPPlayerConfig : NSObject
{
    _Bool _enableP2P;
    _Bool _userIsVip;
    NSString *_guid;
    long long _proxyPlatform;
    NSString *_proxyCacheDir;
    NSString *_proxyDataDir;
    NSString *_proxyConfigDir;
    long long _proxyServiceType;
    NSString *_userUin;
    NSString *_appVersion;
    NSString *_appBuildVersion;
    NSString *_userUpc;
    long long _userUpcState;
    long long _platform;
}

+ (id)sharedInstance;
@property(nonatomic) long long platform; // @synthesize platform=_platform;
@property(nonatomic) long long userUpcState; // @synthesize userUpcState=_userUpcState;
@property(retain, nonatomic) NSString *userUpc; // @synthesize userUpc=_userUpc;
@property(retain, nonatomic) NSString *appBuildVersion; // @synthesize appBuildVersion=_appBuildVersion;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(nonatomic) _Bool userIsVip; // @synthesize userIsVip=_userIsVip;
@property(retain, nonatomic) NSString *userUin; // @synthesize userUin=_userUin;
@property(nonatomic) long long proxyServiceType; // @synthesize proxyServiceType=_proxyServiceType;
@property(retain, nonatomic) NSString *proxyConfigDir; // @synthesize proxyConfigDir=_proxyConfigDir;
@property(retain, nonatomic) NSString *proxyDataDir; // @synthesize proxyDataDir=_proxyDataDir;
@property(retain, nonatomic) NSString *proxyCacheDir; // @synthesize proxyCacheDir=_proxyCacheDir;
@property(nonatomic) long long proxyPlatform; // @synthesize proxyPlatform=_proxyPlatform;
@property(retain, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(nonatomic) _Bool enableP2P; // @synthesize enableP2P=_enableP2P;
- (void).cxx_destruct;

@end

