//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TPPlayerRecord : NSObject
{
    _Bool _useP2p;
    long long _getFirstPacketTime;
    NSString *_definition;
}

@property(nonatomic) _Bool useP2p; // @synthesize useP2p=_useP2p;
@property(retain, nonatomic) NSString *definition; // @synthesize definition=_definition;
@property(nonatomic) long long getFirstPacketTime; // @synthesize getFirstPacketTime=_getFirstPacketTime;
- (void).cxx_destruct;

@end

