//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TPProgramInfo : NSObject
{
    _Bool _actived;
    long long _programId;
    long long _bandwidth;
    NSString *_url;
}

+ (id)programWitProgramId:(long long)arg1 bandwidth:(long long)arg2 url:(id)arg3 actived:(_Bool)arg4;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long bandwidth; // @synthesize bandwidth=_bandwidth;
@property(nonatomic) long long programId; // @synthesize programId=_programId;
@property(nonatomic) _Bool actived; // @synthesize actived=_actived;
- (void).cxx_destruct;

@end

