//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITPReportParams-Protocol.h"

@class NSString;

@interface TPReportParamsStepSeek : NSObject <ITPReportParams>
{
    long long _format;
    long long _pstime;
    long long _petime;
    long long _lstime;
    long long _letime;
    NSString *_code;
}

@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(nonatomic) long long letime; // @synthesize letime=_letime;
@property(nonatomic) long long lstime; // @synthesize lstime=_lstime;
@property(nonatomic) long long petime; // @synthesize petime=_petime;
@property(nonatomic) long long pstime; // @synthesize pstime=_pstime;
@property(nonatomic) long long format; // @synthesize format=_format;
- (void).cxx_destruct;
- (void)setErrorCode:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

