//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITPReportParams-Protocol.h"

@class NSString;

@interface TPReportParamsStepPlayComplete : NSObject <ITPReportParams>
{
    unsigned long long _reason;
    long long _etime;
    double _playduration;
    NSString *_code;
    long long _scount;
    long long _tbcount;
    long long _tbduration;
    long long _bcount;
    long long _tduration;
}

@property(nonatomic) long long tduration; // @synthesize tduration=_tduration;
@property(nonatomic) long long bcount; // @synthesize bcount=_bcount;
@property(nonatomic) long long tbduration; // @synthesize tbduration=_tbduration;
@property(nonatomic) long long tbcount; // @synthesize tbcount=_tbcount;
@property(nonatomic) long long scount; // @synthesize scount=_scount;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(nonatomic) double playduration; // @synthesize playduration=_playduration;
@property(nonatomic) long long etime; // @synthesize etime=_etime;
@property(nonatomic) unsigned long long reason; // @synthesize reason=_reason;
- (void).cxx_destruct;
- (void)setErrorCode:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

