//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TPReportParamsStep.h"

@class NSString;

@interface TPReportParamsStep302 : TPReportParamsStep
{
    NSString *_url;
    long long _vt;
    long long _t302;
}

@property(nonatomic) long long t302; // @synthesize t302=_t302;
@property(nonatomic) long long vt; // @synthesize vt=_vt;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)init;

@end

