//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TPStrategyConfig : NSObject
{
    long long _decoderStrategy;
    NSArray *_playerTypeList;
    long long _playerScene;
}

+ (id)configWithParams:(id)arg1;
@property(nonatomic) long long playerScene; // @synthesize playerScene=_playerScene;
@property(retain, nonatomic) NSArray *playerTypeList; // @synthesize playerTypeList=_playerTypeList;
@property(nonatomic) long long decoderStrategy; // @synthesize decoderStrategy=_decoderStrategy;
- (void).cxx_destruct;

@end

