//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TPSubtitleData : NSObject
{
    NSString *_subtitleData;
    long long _durationMs;
    long long _startPositionMs;
    long long _trackIndex;
}

@property(readonly, nonatomic) long long trackIndex; // @synthesize trackIndex=_trackIndex;
@property(readonly, nonatomic) long long startPositionMs; // @synthesize startPositionMs=_startPositionMs;
@property(readonly, nonatomic) long long durationMs; // @synthesize durationMs=_durationMs;
@property(readonly, copy, nonatomic) NSString *subtitleData; // @synthesize subtitleData=_subtitleData;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1 durationMs:(long long)arg2 startPositionMs:(long long)arg3 trackIndex:(long long)arg4;

@end

