//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TPThumbPlayerWrapper;

@protocol TPThumbPlayerVideoFrameCallback <NSObject>
- (void)onTPVideoFrame:(TPThumbPlayerWrapper *)arg1 frame:(struct TPFrame *)arg2 trackID:(int)arg3 flags:(int)arg4;
@end

