//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface TPUrlDataSource : NSObject
{
    NSString *_originUrl;
    NSString *_thumbPlayerUrl;
    NSString *_systemPlayerUrl;
    NSDictionary *_httpHeader;
}

@property(copy, nonatomic) NSDictionary *httpHeader; // @synthesize httpHeader=_httpHeader;
@property(retain, nonatomic) NSString *systemPlayerUrl; // @synthesize systemPlayerUrl=_systemPlayerUrl;
@property(retain, nonatomic) NSString *thumbPlayerUrl; // @synthesize thumbPlayerUrl=_thumbPlayerUrl;
@property(retain, nonatomic) NSString *originUrl; // @synthesize originUrl=_originUrl;
- (void).cxx_destruct;
- (_Bool)isValid;
- (id)initWithOriginUrl:(id)arg1 thumbPlayerUrl:(id)arg2 systemPlayerUrl:(id)arg3;

@end

