//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TPVCodecCapabilityForGet : NSObject
{
    long long _maxLumaSamples;
    long long _maxProfile;
    long long _maxLevel;
}

@property(nonatomic) long long maxLevel; // @synthesize maxLevel=_maxLevel;
@property(nonatomic) long long maxProfile; // @synthesize maxProfile=_maxProfile;
@property(nonatomic) long long maxLumaSamples; // @synthesize maxLumaSamples=_maxLumaSamples;
- (id)initWithMaxlumaSamples:(long long)arg1 maxProfile:(long long)arg2 maxLevel:(long long)arg3;

@end

