//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TPDefaultReportInfo.h"

@interface TPVodReportInfo : TPDefaultReportInfo
{
    _Bool _hasSubtitles;
    long long _optimizedPlay;
    long long _bizId;
    long long _clipCount;
    long long _videoStatus;
    long long _currentPlayState;
}

@property(nonatomic) long long currentPlayState; // @synthesize currentPlayState=_currentPlayState;
@property(nonatomic) long long videoStatus; // @synthesize videoStatus=_videoStatus;
@property(nonatomic) long long clipCount; // @synthesize clipCount=_clipCount;
@property(nonatomic) long long bizId; // @synthesize bizId=_bizId;
@property(nonatomic) _Bool hasSubtitles; // @synthesize hasSubtitles=_hasSubtitles;
@property(nonatomic) long long optimizedPlay; // @synthesize optimizedPlay=_optimizedPlay;
- (long long)playType;

@end

