//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol TXCBeautyParamSetter <NSObject>
- (void)setMotionMute:(_Bool)arg1;
- (void)setMotionTemplate:(NSString *)arg1;
- (void)setLipsThicknessLevel:(float)arg1;
- (void)setNosePositionLevel:(float)arg1;
- (void)setNoseWingLevel:(float)arg1;
- (void)setMouthShapeLevel:(float)arg1;
- (void)setEyeAngleLevel:(float)arg1;
- (void)setEyeDistanceLevel:(float)arg1;
- (void)setForeheadLevel:(float)arg1;
- (void)setSmileLinesRemoveLevel:(float)arg1;
- (void)setPounchRemoveLevel:(float)arg1;
- (void)setWrinkleRemoveLevel:(float)arg1;
- (void)setToothWhitenLevel:(float)arg1;
- (void)setEyeLightenLevel:(float)arg1;
- (void)setNoseSlimLevel:(float)arg1;
- (void)setFaceShortLevel:(float)arg1;
- (void)setChinLevel:(float)arg1;
- (void)setFaceVLevel:(float)arg1;
- (void)setFaceBeautyLevel:(float)arg1;
- (void)setFaceSlimLevel:(float)arg1;
- (void)setEyeScaleLevel:(float)arg1;
- (void)setRuddinessLevel:(float)arg1;
- (void)setWhitenessLevel:(float)arg1;
- (void)setBeautyLevel:(float)arg1;
- (void)setBeautyStyle:(long long)arg1;
@end

