//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol TXIAudioCoreRecordDelegate <NSObject>

@optional
- (void)onRecordError:(long long)arg1 info:(NSString *)arg2;
- (void)onCorePlayPCMDataToSoftAEC:(const struct _TXSAudioData *)arg1;
- (void)onCoreRecordPCMData:(const struct _TXSAudioData *)arg1 count:(unsigned long long)arg2;
@end

