//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class ZZControlChainModel;

@interface UIControl (ZZFLEX_EX)
+ (CDUnknownBlockType)zz_create;
@property(readonly, copy, nonatomic) ZZControlChainModel *zz_setup;
- (id)controlTargetList;
- (void)removeControlEvents:(unsigned long long)arg1;
- (void)addControlEvents:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;
- (void)removeAllTargets;
@end

