//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class ZZImageViewChainModel;

@interface UIImageView (ZZFLEX_EX)
+ (CDUnknownBlockType)zz_create;
@property(readonly, copy, nonatomic) ZZImageViewChainModel *zz_setup;
- (void)setImage:(id)arg1 highlightedImage:(id)arg2 animationImages:(id)arg3;
- (void)stopRotate;
- (void)startRotate;
- (_Bool)isRotating;
@end

