//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class ZZLabelChainModel;

@interface UILabel (ZZFLEX_EX)
+ (CDUnknownBlockType)zz_create;
@property(readonly, copy, nonatomic) ZZLabelChainModel *zz_setup;
- (void)autoFitAllowMultipleLines;
- (void)autoFit;
- (void)widthToFit;
- (void)heightToFit;
@property(nonatomic) _Bool isCopyable;
- (void)copyText:(id)arg1;
- (void)handleTap:(id)arg1;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)setTextColorWithHex:(id)arg1;
- (void)sizeFitTwoLineMaxWidth:(double)arg1;
- (void)configMaxWidth:(double)arg1;
@property(readonly, nonatomic) double expBottom;
@property(readonly, nonatomic) double expH;
@property(readonly, nonatomic) double expY;
@property(nonatomic) struct CGPoint expOrigin;
@property(nonatomic) struct CGRect expFrame;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2 range:(struct _NSRange)arg3 highlightFont:(id)arg4;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2 range:(struct _NSRange)arg3;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2 startIndex:(unsigned long long)arg3;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2;
@end

