//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIScrollViewDelegate-Protocol.h"

@class FavBrowseDetailData, NSString;

@interface UIScrollViewDelegateHooker : NSObject <UIScrollViewDelegate>
{
    id _originalDelegate;
    FavBrowseDetailData *_browseData;
}

@property(nonatomic) __weak FavBrowseDetailData *browseData; // @synthesize browseData=_browseData;
@property(nonatomic) __weak id originalDelegate; // @synthesize originalDelegate=_originalDelegate;
- (void).cxx_destruct;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (_Bool)respondsToSelector:(SEL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

