//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPageSheet.h"

#import "WAPopInteractiveTransitionDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UIScreenEdgePanGestureRecognizer, UIScrollView, UIView, WAMenuPopInteractiveTransition;
@protocol IWARichTextViewService;

@interface WAAuthorizeInfoPageSheet : WAPageSheet <WAPopInteractiveTransitionDelegate>
{
    CDUnknownBlockType _dismissAction;
    CDUnknownBlockType _openUrlAction;
    UIButton *_backButton;
    UILabel *_titleLabel;
    id <IWARichTextViewService> _textViewProxy;
    UIView *_textView;
    UIScrollView *_scrollView;
    NSString *_title;
    NSString *_info;
    WAMenuPopInteractiveTransition *_popIT;
    UIScreenEdgePanGestureRecognizer *_panGR;
}

@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *panGR; // @synthesize panGR=_panGR;
@property(retain, nonatomic) WAMenuPopInteractiveTransition *popIT; // @synthesize popIT=_popIT;
@property(readonly, nonatomic) NSString *info; // @synthesize info=_info;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) id <IWARichTextViewService> textViewProxy; // @synthesize textViewProxy=_textViewProxy;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(copy, nonatomic) CDUnknownBlockType openUrlAction; // @synthesize openUrlAction=_openUrlAction;
@property(copy, nonatomic) CDUnknownBlockType dismissAction; // @synthesize dismissAction=_dismissAction;
- (void).cxx_destruct;
- (void)onPopBackInteractiveTransitionBegin:(id)arg1;
- (void)backButtonClick:(id)arg1;
- (double)contentHeight;
- (void)layoutSubViews;
- (void)_setupUI;
- (id)initWithInfo:(id)arg1;
- (id)initWithTitle:(id)arg1 info:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

