//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAAuthorizePageSheet.h"

#import "ILinkEventExt-Protocol.h"

@class MMCheckBox, MMUIButton, NSString, PhoneInfo, RichTextView, UILabel, UITableView, UIView, UserIdAuthorizePageInfo, ZZFLEXAngel;

@interface WAAuthorizeUserIdPageSheet : WAAuthorizePageSheet <ILinkEventExt>
{
    UserIdAuthorizePageInfo *_pageInfo;
    CDUnknownBlockType _managerPhoneNumberAction;
    UIView *_auiView;
    UILabel *_idLabel;
    UILabel *_phoneTitleLabel;
    UITableView *_phoneView;
    ZZFLEXAngel *_phoneAngel;
    MMUIButton *_managerButton;
    UIView *_protocolView;
    MMCheckBox *_protocolJumpCheckBox;
    RichTextView *_protocolJumpRichText;
    PhoneInfo *_selectedItem;
}

@property(retain, nonatomic) PhoneInfo *selectedItem; // @synthesize selectedItem=_selectedItem;
@property(retain, nonatomic) RichTextView *protocolJumpRichText; // @synthesize protocolJumpRichText=_protocolJumpRichText;
@property(retain, nonatomic) MMCheckBox *protocolJumpCheckBox; // @synthesize protocolJumpCheckBox=_protocolJumpCheckBox;
@property(retain, nonatomic) UIView *protocolView; // @synthesize protocolView=_protocolView;
@property(retain, nonatomic) MMUIButton *managerButton; // @synthesize managerButton=_managerButton;
@property(retain, nonatomic) ZZFLEXAngel *phoneAngel; // @synthesize phoneAngel=_phoneAngel;
@property(retain, nonatomic) UITableView *phoneView; // @synthesize phoneView=_phoneView;
@property(retain, nonatomic) UILabel *phoneTitleLabel; // @synthesize phoneTitleLabel=_phoneTitleLabel;
@property(retain, nonatomic) UILabel *idLabel; // @synthesize idLabel=_idLabel;
@property(retain, nonatomic) UIView *auiView; // @synthesize auiView=_auiView;
@property(copy, nonatomic) CDUnknownBlockType managerPhoneNumberAction; // @synthesize managerPhoneNumberAction=_managerPhoneNumberAction;
@property(retain, nonatomic) UserIdAuthorizePageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
- (void).cxx_destruct;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (double)tableViewHeight;
- (double)contentHeight;
- (void)onAcceptBtnClick:(id)arg1;
- (void)setupAUIPageSheetUI;
- (id)initWithPageInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

