//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "ZZFlexibleLayoutViewProtocol-Protocol.h"

@class NSString, UIImageView, UILabel;

@interface WAAuthorizeUserIdPhoneCell : UITableViewCell <ZZFlexibleLayoutViewProtocol>
{
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIImageView *_markView;
}

+ (double)viewHeightByDataModel:(id)arg1;
@property(retain, nonatomic) UIImageView *markView; // @synthesize markView=_markView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)setWXPhone:(_Bool)arg1;
- (void)setMark:(_Bool)arg1;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)onViewPositionUpdatedWithIndexPath:(id)arg1 sectionItemCount:(long long)arg2;
- (void)setViewDataModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

