//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface WACacheVersionPreCheckerContextResult : NSObject
{
    _Bool _hasResult;
    _Bool _checkSuccess;
    NSMutableArray *_needDownloadInfoDatas;
    NSMutableArray *_downloadSuccessInfoDatas;
    NSMutableArray *_checkPassInfoDatas;
    NSMutableArray *_checkFailedInfoDatas;
    NSMutableArray *_checkAutoUpdateInfoDatas;
}

@property(retain, nonatomic) NSMutableArray *checkAutoUpdateInfoDatas; // @synthesize checkAutoUpdateInfoDatas=_checkAutoUpdateInfoDatas;
@property(retain, nonatomic) NSMutableArray *checkFailedInfoDatas; // @synthesize checkFailedInfoDatas=_checkFailedInfoDatas;
@property(retain, nonatomic) NSMutableArray *checkPassInfoDatas; // @synthesize checkPassInfoDatas=_checkPassInfoDatas;
@property(retain, nonatomic) NSMutableArray *downloadSuccessInfoDatas; // @synthesize downloadSuccessInfoDatas=_downloadSuccessInfoDatas;
@property(retain, nonatomic) NSMutableArray *needDownloadInfoDatas; // @synthesize needDownloadInfoDatas=_needDownloadInfoDatas;
@property(nonatomic) _Bool checkSuccess; // @synthesize checkSuccess=_checkSuccess;
@property(nonatomic) _Bool hasResult; // @synthesize hasResult=_hasResult;
- (void).cxx_destruct;

@end

