//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

#import "TXLivePlayJSAdapterDelegate-Protocol.h"
#import "WAFloatingVideoDelegate-Protocol.h"
#import "WAVideoPlayerViewDelegate-Protocol.h"

@class NSString, UINavigationController, WAFloatingVideoView, WAFloatingViewBaseWrapper, WAWebViewController;

@interface WAJSContextPlugin_FloatVideo : WAJSContextPluginBase <WAFloatingVideoDelegate, WAVideoPlayerViewDelegate, TXLivePlayJSAdapterDelegate>
{
    _Bool _hasRecovered;
    _Bool _needRemoveFloatViewAfterTransitioning;
    _Bool _isFloatingVideoMinimizing;
    _Bool _needRemoveFloatViewAfterPop;
    WAWebViewController *_webviewController;
    WAFloatingViewBaseWrapper *_floatingViewWrapper;
    WAFloatingVideoView *_floatingVideoView;
    UINavigationController *_currentNavigationController;
}

@property(nonatomic) _Bool needRemoveFloatViewAfterPop; // @synthesize needRemoveFloatViewAfterPop=_needRemoveFloatViewAfterPop;
@property(nonatomic) _Bool isFloatingVideoMinimizing; // @synthesize isFloatingVideoMinimizing=_isFloatingVideoMinimizing;
@property(nonatomic) _Bool needRemoveFloatViewAfterTransitioning; // @synthesize needRemoveFloatViewAfterTransitioning=_needRemoveFloatViewAfterTransitioning;
@property(nonatomic) _Bool hasRecovered; // @synthesize hasRecovered=_hasRecovered;
@property(nonatomic) __weak UINavigationController *currentNavigationController; // @synthesize currentNavigationController=_currentNavigationController;
@property(retain, nonatomic) WAFloatingVideoView *floatingVideoView; // @synthesize floatingVideoView=_floatingVideoView;
@property(retain, nonatomic) WAFloatingViewBaseWrapper *floatingViewWrapper; // @synthesize floatingViewWrapper=_floatingViewWrapper;
@property(retain, nonatomic) WAWebViewController *webviewController; // @synthesize webviewController=_webviewController;
- (void).cxx_destruct;
- (void)dataReportWithEventId:(unsigned long long)arg1 eventNote:(unsigned long long)arg2;
- (void)reportFloatVideoWhenDisappeared:(id)arg1;
- (void)sendEventWithFloatingValue:(id)arg1 service:(id)arg2 videoKey:(id)arg3 webview:(id)arg4;
- (void)sendEventWithFloatingValue:(long long)arg1 webview:(id)arg2;
- (void)sendPlayerMaxEvent:(id)arg1;
- (void)sendPlayerMinEvent:(id)arg1;
- (void)didRotate:(id)arg1;
- (void)willRotate:(id)arg1;
- (void)dealloc;
- (void)onPlayEvent:(int)arg1 evtMsg:(id)arg2 playerId:(unsigned int)arg3 param:(id)arg4;
- (void)onVideoPlay:(double)arg1 duration:(double)arg2;
- (void)onVideoStateChange:(long long)arg1;
- (_Bool)isWebViewInPageStack;
- (void)onFloatingVideoViewClicked;
- (void)onFloatingVideoViewClosed;
- (void)onVideoPauseFromWebView:(id)arg1 playerId:(unsigned int)arg2;
- (void)onVideoStartPlayingFromWebView:(id)arg1 playerId:(unsigned int)arg2 autoPlay:(_Bool)arg3;
- (unsigned int)getFloatingVideoId;
- (id)getFloatingVideoView;
- (_Bool)isFloatingVideoExist;
- (void)resetPlayerParamAndRemoveView:(_Bool)arg1;
- (void)reset;
- (void)resetFloatingVideoParams:(_Bool)arg1;
- (void)setFloatingVideoParams;
- (_Bool)operateFloatVideoWithDic:(id)arg1 playerId:(unsigned int)arg2;
- (_Bool)closeFloatingVideoView;
- (void)closeForRelaunch;
- (_Bool)recoverFloatingVideoView;
- (_Bool)removeFloatingVideoView;
- (struct CGRect)getFloatingVideoViewFrame:(id)arg1 orientation:(long long)arg2;
- (void)showWithContext:(id)arg1 type:(long long)arg2;
- (void)maximizedFloatingView:(id)arg1;
- (void)minimizedFloatingView:(id)arg1;
- (struct CGRect)correctFrame:(struct CGRect)arg1;
- (id)getPlayerViewSnapShotView:(struct CGRect)arg1 contentMode:(long long)arg2 addToVideoView:(_Bool)arg3;
- (_Bool)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (id)currentAppTask;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

