//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "IWAJSContextBlueToothProtocol-Protocol.h"

@class NSString;

@interface WAJSEventHandler_getBLEDeviceRSSI : WAJSEventHandler_BaseEvent <IWAJSContextBlueToothProtocol>
{
    NSString *_deviceUUID;
}

@property(copy, nonatomic) NSString *deviceUUID; // @synthesize deviceUUID=_deviceUUID;
- (void).cxx_destruct;
- (void)onBLEDevice:(id)arg1 didReadRSSI:(id)arg2 errorCode:(int)arg3 errMsg:(id)arg4 appId:(id)arg5;
- (void)handleJSEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

