//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WALaunchTimeAxisEventNode : NSObject
{
    unsigned int _option;
    NSString *_appid;
    NSString *_parentPhase;
    NSString *_event;
    unsigned long long _category;
    unsigned long long _eventType;
    unsigned long long _timestamp;
}

@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned int option; // @synthesize option=_option;
@property(nonatomic) unsigned long long eventType; // @synthesize eventType=_eventType;
@property(nonatomic) unsigned long long category; // @synthesize category=_category;
@property(copy, nonatomic) NSString *event; // @synthesize event=_event;
@property(copy, nonatomic) NSString *parentPhase; // @synthesize parentPhase=_parentPhase;
@property(copy, nonatomic) NSString *appid; // @synthesize appid=_appid;
- (void).cxx_destruct;

@end

