//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface WAOpenSetting_SubscriptionsModel : NSObject
{
    _Bool _mainSwitch;
    NSArray *_templatesInfo;
}

@property(retain, nonatomic) NSArray *templatesInfo; // @synthesize templatesInfo=_templatesInfo;
@property(nonatomic) _Bool mainSwitch; // @synthesize mainSwitch=_mainSwitch;
- (void).cxx_destruct;

@end

