//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportPluginAutoUpdateStatisItem : WAReportBaseItem
{
    NSString *_pluginAppid;
    long long _pluginVersion;
    long long _pluginState;
    NSString *_instanceId;
    long long _updateScene;
    long long _updateResult;
}

@property(nonatomic) long long updateResult; // @synthesize updateResult=_updateResult;
@property(nonatomic) long long updateScene; // @synthesize updateScene=_updateScene;
@property(retain, nonatomic) NSString *instanceId; // @synthesize instanceId=_instanceId;
@property(nonatomic) long long pluginState; // @synthesize pluginState=_pluginState;
@property(nonatomic) long long pluginVersion; // @synthesize pluginVersion=_pluginVersion;
@property(retain, nonatomic) NSString *pluginAppid; // @synthesize pluginAppid=_pluginAppid;
- (void).cxx_destruct;
- (id)reportString;
- (void)makeSafeString;
- (int)reportID;

@end

