//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportTaskBarExposureItem : WAReportBaseItem
{
    NSString *_openSession;
    NSString *_recentShowAppIdList;
    NSString *_starShowAppIdList;
}

@property(copy, nonatomic) NSString *starShowAppIdList; // @synthesize starShowAppIdList=_starShowAppIdList;
@property(copy, nonatomic) NSString *recentShowAppIdList; // @synthesize recentShowAppIdList=_recentShowAppIdList;
@property(copy, nonatomic) NSString *openSession; // @synthesize openSession=_openSession;
- (void).cxx_destruct;
- (id)reportString;

@end

