//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ILinkEventExt-Protocol.h"
#import "IWARichTextViewService-Protocol.h"

@class NSString;

@interface WARichTextViewProxy : NSObject <ILinkEventExt, IWARichTextViewService>
{
    CDUnknownBlockType _linkClickAction;
}

@property(copy, nonatomic) CDUnknownBlockType linkClickAction; // @synthesize linkClickAction=_linkClickAction;
- (void).cxx_destruct;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (id)getRichTextViewByHtmlCode:(id)arg1 frame:(struct CGRect)arg2 clickAction:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

