//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMWebImageView, NSArray, UIImageView, UILabel, WAWebViewBottomBannerViewModel;
@protocol WAWebviewBottomBannerViewDelegate;

@interface WAWebviewBottomBannerView : UIView
{
    WAWebViewBottomBannerViewModel *_viewModel;
    id <WAWebviewBottomBannerViewDelegate> _delegate;
    MMWebImageView *_iconImgView;
    UIView *_mmHeadImageView;
    UILabel *_titleLabel;
    UILabel *_titleTailLabel;
    UIImageView *_leftCornerImgView;
    UIImageView *_rightCornerImgView;
    NSArray *_buttons;
}

@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) UIImageView *rightCornerImgView; // @synthesize rightCornerImgView=_rightCornerImgView;
@property(retain, nonatomic) UIImageView *leftCornerImgView; // @synthesize leftCornerImgView=_leftCornerImgView;
@property(retain, nonatomic) UILabel *titleTailLabel; // @synthesize titleTailLabel=_titleTailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *mmHeadImageView; // @synthesize mmHeadImageView=_mmHeadImageView;
@property(retain, nonatomic) MMWebImageView *iconImgView; // @synthesize iconImgView=_iconImgView;
@property(nonatomic) __weak id <WAWebviewBottomBannerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAWebViewBottomBannerViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)onButtonClicked:(id)arg1;
- (void)generateButtons;
- (void)reloadData;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

