//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableArray, WAAppTask;

@interface WAWebViewPageMgr : MMObject
{
    NSMutableArray *_pages;
    NSMutableArray *_removedPages;
    NSMutableArray *_stackPages;
    NSMutableArray *_releasePool;
    NSMutableArray *_dissociativePool;
    WAAppTask *_task;
}

@property(nonatomic) __weak WAAppTask *task; // @synthesize task=_task;
@property(retain, nonatomic) NSMutableArray *dissociativePool; // @synthesize dissociativePool=_dissociativePool;
@property(retain, nonatomic) NSMutableArray *releasePool; // @synthesize releasePool=_releasePool;
@property(retain, nonatomic) NSMutableArray *stackPages; // @synthesize stackPages=_stackPages;
@property(retain, nonatomic) NSMutableArray *removedPages; // @synthesize removedPages=_removedPages;
@property(retain, nonatomic) NSMutableArray *pages; // @synthesize pages=_pages;
- (void).cxx_destruct;
- (unsigned int)stackPagesCount;
- (unsigned int)healthyPagesCount;
- (unsigned int)manuallyTerminatedPagesCount;
- (unsigned int)contentProcessTerminatedPagesCount;
- (id)pagesStatusDescription;
- (void)popAllDissociativeWebview;
- (void)popAllWebViewPage;
- (void)removeAllPageDelegates;
- (_Bool)isTopMostPage:(id)arg1;
- (id)topMostPage;
- (id)lastPage;
- (id)firstPage;
- (unsigned long long)webviewInPagesIndex:(id)arg1;
- (unsigned long long)pagesCount;
- (void)checkReleasePool;
- (void)checkStack;
- (void)popDissociativeWebViewPage:(id)arg1;
- (void)pushDissociativeWebViewPage:(id)arg1;
- (void)popWebViewPage:(id)arg1;
- (void)pushWebViewPage:(id)arg1;
- (id)initWithTask:(id)arg1;

@end

