//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "WAPageSheetDelegate-Protocol.h"
#import "WCAdSubscriptionPageSheetDelegate-Protocol.h"

@class NSString;
@protocol WCAdSubscriptionLogicDelegate;

@interface WCAdSubscriptionLogic : MMObject <WCAdSubscriptionPageSheetDelegate, WAPageSheetDelegate>
{
    _Bool _btnHasBeenClicked;
    unsigned int _appType;
    id <WCAdSubscriptionLogicDelegate> _delegate;
    NSString *_templateID;
    NSString *_username;
    NSString *_appid;
    NSString *_adTitle;
    NSString *_adDesc;
    NSString *_adSubmitBtnTitle;
}

@property(nonatomic) _Bool btnHasBeenClicked; // @synthesize btnHasBeenClicked=_btnHasBeenClicked;
@property(retain, nonatomic) NSString *adSubmitBtnTitle; // @synthesize adSubmitBtnTitle=_adSubmitBtnTitle;
@property(retain, nonatomic) NSString *adDesc; // @synthesize adDesc=_adDesc;
@property(retain, nonatomic) NSString *adTitle; // @synthesize adTitle=_adTitle;
@property(nonatomic) unsigned int appType; // @synthesize appType=_appType;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *templateID; // @synthesize templateID=_templateID;
@property(nonatomic) __weak id <WCAdSubscriptionLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)pageSheetWillHide:(id)arg1;
- (void)onCloseBtnClick;
- (void)onSubmitBtnClick:(id)arg1;
- (CDUnknownBlockType)requestSubscribeFailHandler;
- (CDUnknownBlockType)requestSubscribeSuccessHandler;
- (CDUnknownBlockType)requestListByIDFailHandler;
- (CDUnknownBlockType)requestListByIDSucceessHandler;
- (id)fetchUIView;
- (void)callFinishedDelegateWithResult:(id)arg1 success:(_Bool)arg2 cancel:(_Bool)arg3 errorCode:(long long)arg4;
- (void)sendSubscribeRequestWithViewModel:(id)arg1;
- (void)sendSubscriptionRequest;
- (void)checkParameterAndStart;
- (void)start;
- (id)initWithTemplateID:(id)arg1 username:(id)arg2 appid:(id)arg3 appType:(unsigned int)arg4 adTitle:(id)arg5 adDesc:(id)arg6 adSubmitBtnTitle:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

