//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

@interface WCFinderRegionPickerTableViewCell : MMTableViewCell
{
}

- (void)setText:(id)arg1 accessoryType:(long long)arg2;
- (void)setText:(id)arg1 image:(id)arg2 accessoryType:(long long)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

