//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel, WCFinderAnimationLoadingView;

@interface WCFinderSubCommentMoreTableViewCell : UITableViewCell
{
    UILabel *_moreInfoLabel;
    WCFinderAnimationLoadingView *_loadingView;
    unsigned long long _moreType;
    UIButton *_iconView;
}

@property(nonatomic) __weak UIButton *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) unsigned long long moreType; // @synthesize moreType=_moreType;
@property(nonatomic) __weak WCFinderAnimationLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) __weak UILabel *moreInfoLabel; // @synthesize moreInfoLabel=_moreInfoLabel;
- (void).cxx_destruct;
- (void)stopLoadingAnimation;
- (void)startLoadingAnimation;
- (void)setUpUI;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSubMoreType:(unsigned long long)arg1 commentMoreCount:(unsigned long long)arg2 authorType:(unsigned long long)arg3;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

