//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MMTableView, NSMutableArray, NSString;
@protocol WCFinderRegionPickerViewControllerDelegate;

@interface WCFinderRegionPickerViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _showRealTimeLocation;
    id <WCFinderRegionPickerViewControllerDelegate> _delegate;
    unsigned long long _selectedIndex;
    NSString *_disPlayFinderLocation;
    NSMutableArray *_realTimeLocation;
    NSString *_disPlayrealTimeLocation;
    MMTableView *_tableView;
}

@property(nonatomic, getter=isShowRealTimeLocation) _Bool showRealTimeLocation; // @synthesize showRealTimeLocation=_showRealTimeLocation;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *disPlayrealTimeLocation; // @synthesize disPlayrealTimeLocation=_disPlayrealTimeLocation;
@property(retain, nonatomic) NSMutableArray *realTimeLocation; // @synthesize realTimeLocation=_realTimeLocation;
@property(copy, nonatomic) NSString *disPlayFinderLocation; // @synthesize disPlayFinderLocation=_disPlayFinderLocation;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) __weak id <WCFinderRegionPickerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onReturn;
- (void)onDone;
- (void)setupTableView;
- (void)setupNavitationBar;
- (void)setupSubViews;
- (void)viewDidLoad;
- (id)initWithFinderLocationStr:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

