//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderPreloadInfo : NSObject
{
    unsigned long long _preloadVideoCount;
    unsigned long long _preloadVideoThreadCount;
    unsigned long long _preloadStrategyID;
}

@property(nonatomic) unsigned long long preloadStrategyID; // @synthesize preloadStrategyID=_preloadStrategyID;
@property(nonatomic) unsigned long long preloadVideoThreadCount; // @synthesize preloadVideoThreadCount=_preloadVideoThreadCount;
@property(nonatomic) unsigned long long preloadVideoCount; // @synthesize preloadVideoCount=_preloadVideoCount;

@end

