//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPlayerReporter.h"

@interface WCFinderPlayerReport : WCPlayerReporter
{
    _Bool _downloadSuccessful;
    _Bool _isDownloadH265;
    _Bool _hasFinderDataReported;
    unsigned long long _hasDownloadSize;
}

@property(nonatomic) _Bool hasFinderDataReported; // @synthesize hasFinderDataReported=_hasFinderDataReported;
@property(nonatomic) _Bool isDownloadH265; // @synthesize isDownloadH265=_isDownloadH265;
@property(nonatomic) _Bool downloadSuccessful; // @synthesize downloadSuccessful=_downloadSuccessful;
@property(nonatomic) unsigned long long hasDownloadSize; // @synthesize hasDownloadSize=_hasDownloadSize;
- (long long)getPreloadFileSize;
- (id)replaceCommaToSemicolon:(id)arg1;
- (id)getWaitDetailJson;
- (id)getReportInfo;
- (void)reportPlayerInfo;

@end

