//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCEditVideoViewController.h"

@interface WCFinderEditVideoTimeViewController : WCEditVideoViewController
{
    _Bool _directlyToCropVideoTime;
}

@property(nonatomic) _Bool directlyToCropVideoTime; // @synthesize directlyToCropVideoTime=_directlyToCropVideoTime;
- (void)showEditVideoViewOn:(id)arg1;
- (_Bool)isExceedTimelineTimeLimit;
- (float)getOutputTime;
- (long long)preferredStatusBarStyle;
- (_Bool)hidesStatusBar;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithVideoPath:(id)arg1 thumbImage:(id)arg2 directlyToCropVideoTime:(_Bool)arg3;

@end

