//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol WCFinderFeedContentHeaderActionDelegate;

@interface WCFinderFeedContentHeaderView : UIView
{
    _Bool _shouldNickNameBeLinkColor;
    _Bool _shouldFollowBtnHidden;
    _Bool _shouldMoreBtnHidden;
    _Bool _shouldShowFollowTips;
    id <WCFinderFeedContentHeaderActionDelegate> _delegate;
    unsigned long long _type;
}

+ (double)headerHeightForType:(unsigned long long)arg1;
+ (id)headerWithType:(unsigned long long)arg1 width:(double)arg2;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) _Bool shouldShowFollowTips; // @synthesize shouldShowFollowTips=_shouldShowFollowTips;
@property(nonatomic) _Bool shouldMoreBtnHidden; // @synthesize shouldMoreBtnHidden=_shouldMoreBtnHidden;
@property(nonatomic) _Bool shouldFollowBtnHidden; // @synthesize shouldFollowBtnHidden=_shouldFollowBtnHidden;
@property(nonatomic) _Bool shouldNickNameBeLinkColor; // @synthesize shouldNickNameBeLinkColor=_shouldNickNameBeLinkColor;
@property(nonatomic) __weak id <WCFinderFeedContentHeaderActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)hideFollowViewIfNeeded;
- (void)resetReuseState;
- (void)reloadHeaderWithContact:(id)arg1;
- (void)updateHeaderContentWithContact:(id)arg1;

@end

