//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ForwardMessageLogicDelegate-Protocol.h"
#import "MMScrollActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCFinderCommentDatailViewControllerDelegate-Protocol.h"
#import "WCFinderCommentIdentityViewControllerDelegate-Protocol.h"
#import "WCFinderContentTableViewCellDelegate-Protocol.h"
#import "WCFinderFeedCommentTableViewCellDelegate-Protocol.h"
#import "WCFinderFeedDetailStatusViewDelegate-Protocol.h"
#import "WCFinderFeedShareFooterCelDelegate-Protocol.h"
#import "WCFinderMulitMediaTableViewCellDelegate-Protocol.h"
#import "WCFinderPostingCommentExt-Protocol.h"
#import "WCFinderShareDetailViewModelDelegate-Protocol.h"
#import "WCFinderToolbarTableViewCellDelegate-Protocol.h"
#import "WCFinderVideoPlayerExt-Protocol.h"
#import "WCGeneralListMonitorExt-Protocol.h"

@class ForwardMessageLogicController, NSString, UITableView, WCFinderCommentDatailViewController, WCFinderCreateCoordinator, WCFinderFeedDetailStatusView, WCFinderShareDetailViewModel;

@interface WCFinderShareDetailViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, ForwardMessageLogicDelegate, WCFinderFeedShareFooterCelDelegate, WCFinderMulitMediaTableViewCellDelegate, WCFinderContentTableViewCellDelegate, WCFinderToolbarTableViewCellDelegate, WCFinderFeedCommentTableViewCellDelegate, MMScrollActionSheetDelegate, WCFinderFeedDetailStatusViewDelegate, WCFinderPostingCommentExt, WCFinderShareDetailViewModelDelegate, WCGeneralListMonitorExt, WCFinderCommentDatailViewControllerDelegate, WCFinderCommentIdentityViewControllerDelegate, WCFinderVideoPlayerExt>
{
    _Bool _isSilencePlay;
    _Bool _needResumeMusicPlay;
    _Bool _extranceSwitch;
    _Bool _needsResumeTimelineVideo;
    NSString *_contentTid;
    NSString *_shareEnterUsername;
    UITableView *_tableView;
    ForwardMessageLogicController *_forwardLogic;
    double _startExposureTime;
    WCFinderCreateCoordinator *_createCoordinator;
    WCFinderFeedDetailStatusView *_statusView;
    WCFinderShareDetailViewModel *_viewModel;
    WCFinderCommentDatailViewController *_lastCommentVC;
    double _currentVideoPlayProgress;
}

@property(nonatomic) _Bool needsResumeTimelineVideo; // @synthesize needsResumeTimelineVideo=_needsResumeTimelineVideo;
@property(nonatomic) double currentVideoPlayProgress; // @synthesize currentVideoPlayProgress=_currentVideoPlayProgress;
@property(retain, nonatomic) WCFinderCommentDatailViewController *lastCommentVC; // @synthesize lastCommentVC=_lastCommentVC;
@property(nonatomic) _Bool extranceSwitch; // @synthesize extranceSwitch=_extranceSwitch;
@property(retain, nonatomic) WCFinderShareDetailViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) _Bool needResumeMusicPlay; // @synthesize needResumeMusicPlay=_needResumeMusicPlay;
@property(retain, nonatomic) WCFinderFeedDetailStatusView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) WCFinderCreateCoordinator *createCoordinator; // @synthesize createCoordinator=_createCoordinator;
@property(nonatomic) double startExposureTime; // @synthesize startExposureTime=_startExposureTime;
@property(nonatomic) _Bool isSilencePlay; // @synthesize isSilencePlay=_isSilencePlay;
@property(retain, nonatomic) ForwardMessageLogicController *forwardLogic; // @synthesize forwardLogic=_forwardLogic;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSString *shareEnterUsername; // @synthesize shareEnterUsername=_shareEnterUsername;
@property(retain, nonatomic) NSString *contentTid; // @synthesize contentTid=_contentTid;
- (void).cxx_destruct;
- (void)clickCommentNickname:(id)arg1 username:(id)arg2 contact:(id)arg3 isWeChatFriend:(_Bool)arg4;
- (void)onFinderVideoPlayerStartPlay;
- (void)onFinderDataItemPostingCommentFailBySpecialError:(id)arg1 errorCode:(int)arg2 errorMsg:(id)arg3;
- (void)didClickRetry:(id)arg1;
- (void)didClickBack:(id)arg1;
- (_Bool)enableFeedShare;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (void)onClickCommentUserName:(id)arg1;
- (void)finderCommentCell:(id)arg1 didClickCommentLikeWithcomment:(id)arg2 contentVM:(id)arg3;
- (void)onClickCommentAction:(id)arg1 contentVM:(id)arg2;
- (void)showCommentActionSheetWithComment:(id)arg1 contentVM:(id)arg2;
- (void)onClickContentTopicAction:(id)arg1 dataItem:(id)arg2;
- (void)onClickContentExtReadingAction:(id)arg1;
- (void)onContentTableViewCell:(id)arg1 longPressContentAction:(id)arg2 rect:(struct CGRect)arg3;
- (void)onClickContentReadMoreAction:(id)arg1 isExpand:(_Bool)arg2;
- (void)clickContentPOIAction:(id)arg1;
- (void)profileViewDidClickFullTextWithTid:(id)arg1;
- (id)getItemArrayConfig;
- (void)onClickViewAllCommentAction:(id)arg1 isActiveInput:(_Bool)arg2;
- (void)onClickToolbarLikeAction:(id)arg1;
- (void)onHeaderMoreClickAction:(id)arg1;
- (void)onFeedVideoStopPlay:(id)arg1 tid:(id)arg2;
- (void)contentMediaDidEndPlay:(unsigned long long)arg1 contentVM:(id)arg2;
- (void)retryLoadingVideoResource:(_Bool)arg1;
- (void)photoContentPageTurning:(id)arg1 currentPage:(unsigned long long)arg2 lastPage:(unsigned long long)arg3;
- (void)followUserName:(id)arg1 isFollowing:(_Bool)arg2;
- (void)onFeedFollowStatusChanged:(id)arg1 isFollow:(_Bool)arg2 contentVM:(id)arg3;
- (void)showSpamTipsWithString:(id)arg1;
- (void)likeFeedContentVMAction:(id)arg1;
- (void)didFeedDoubleLikeAction:(id)arg1;
- (void)onFeedCellDidClickHeaderView:(id)arg1 contentVM:(id)arg2;
- (void)didSelectVideoMediaMuteChanged:(_Bool)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (id)specialParamsForFeedId:(id)arg1;
- (void)reloadDataWrap;
- (id)getListView;
- (id)feedIdByIndex:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)onFinderBtnClick;
- (id)getCurrentViewController;
- (void)onDataRefreshed;
- (void)onCommentDataChanged;
- (void)onLikeDataChanged;
- (void)onStateOfNotExist;
- (void)onStateOfRefreshNormalError;
- (void)requestData;
- (void)onStateOfContentDeleted;
- (void)onStateOfRetry;
- (void)updateCurrentVideoThumb;
- (void)resetCurrentVideoThumb;
- (void)needsUpdateCurrentVideo:(_Bool)arg1;
- (void)stopVideoPlay;
- (void)startVideoPlay;
- (void)throttleStartPlayProcess;
- (void)onTimelineViewEnterBackground:(id)arg1;
- (void)onTimelineViewEnterForeground:(id)arg1;
- (void)removeObserverForForegroundNotification;
- (void)addObserverForForegroundNotification;
- (void)willDisappear;
- (void)viewDidPushOrPresent:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

