//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUIButton, UILabel;
@protocol WCFinderFeedToolbarActionDelegate;

@interface WCFinderFeedNewToolbarView : UIView
{
    _Bool _isLiked;
    _Bool _isHiddenComment;
    _Bool _isCommentClose;
    id <WCFinderFeedToolbarActionDelegate> _delegate;
    UILabel *_tipsLabel;
    unsigned long long _likeNums;
    UILabel *_likeNumLabel;
    MMUIButton *_likeBtn;
    UIView *_likeMiddleView;
    unsigned long long _commentNums;
    UILabel *_commentNumLabel;
    MMUIButton *_commentBtn;
    UIView *_commentMiddleView;
}

@property(retain, nonatomic) UIView *commentMiddleView; // @synthesize commentMiddleView=_commentMiddleView;
@property(retain, nonatomic) MMUIButton *commentBtn; // @synthesize commentBtn=_commentBtn;
@property(retain, nonatomic) UILabel *commentNumLabel; // @synthesize commentNumLabel=_commentNumLabel;
@property(nonatomic) unsigned long long commentNums; // @synthesize commentNums=_commentNums;
@property(nonatomic) _Bool isCommentClose; // @synthesize isCommentClose=_isCommentClose;
@property(nonatomic) _Bool isHiddenComment; // @synthesize isHiddenComment=_isHiddenComment;
@property(retain, nonatomic) UIView *likeMiddleView; // @synthesize likeMiddleView=_likeMiddleView;
@property(retain, nonatomic) MMUIButton *likeBtn; // @synthesize likeBtn=_likeBtn;
@property(retain, nonatomic) UILabel *likeNumLabel; // @synthesize likeNumLabel=_likeNumLabel;
@property(nonatomic) unsigned long long likeNums; // @synthesize likeNums=_likeNums;
@property(nonatomic) _Bool isLiked; // @synthesize isLiked=_isLiked;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(nonatomic) __weak id <WCFinderFeedToolbarActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didClickCommentBtn:(id)arg1;
- (void)didClickLikeBtn:(id)arg1;
- (void)updateCenterAlignment;
- (void)updateLikeContainer;
- (void)updateCommentContaier;
- (void)updateCommentCount:(long long)arg1 commentClose:(_Bool)arg2 isHiddenComment:(_Bool)arg3 isLiked:(_Bool)arg4 likeNum:(unsigned long long)arg5 tips:(id)arg6;
- (void)setupSubView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

