//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface WCFinderRedDotMgr : NSObject
{
    NSMutableDictionary *_dicPathInfo;
    NSMutableDictionary *_dicTipsInfo;
}

@property(retain, nonatomic) NSMutableDictionary *dicTipsInfo; // @synthesize dicTipsInfo=_dicTipsInfo;
@property(retain, nonatomic) NSMutableDictionary *dicPathInfo; // @synthesize dicPathInfo=_dicPathInfo;
- (void).cxx_destruct;
- (unsigned long long)ctrlInfoTypeAtPath:(id)arg1;
- (void)disposeRedDotAtPath:(id)arg1;
- (id)currentCtrlInfoAtPath:(id)arg1;
- (id)currentShowInfoAtPath:(id)arg1;
- (_Bool)shouldShowRedDotAtPath:(id)arg1;
- (void)addNewRedDotCtrlInfo:(id)arg1;
- (void)loadTipsInfoFromFile;
- (void)cleanCurrentData;
- (void)saveNewTipsBusinessInfos:(id)arg1;
- (id)init;
- (void)buildPreloadUnFollowRedDot:(id)arg1;
- (void)buildPreloadFollowRedDot:(id)arg1;
- (void)buildCompatibleFinderEntranceRedDot;
- (void)buildCompatibleTLPresonalRedDot;
- (void)buildCompatibleTLCameraRedDot;
- (id)mockFinderPrefetchBuildShowInfo;
- (id)mockTLWxMentionBoubleShowInfo;
- (id)mockTLPersonalCenterShowInfo;
- (id)mockCameraShowInfo;
- (id)mockEntanceShowInfo;
- (id)mockTabShowInfo;

@end

