//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMUIViewController, NSString, WCFinderContact;

@protocol WCFinderCommentDatailViewControllerDelegate <NSObject>

@optional
- (void)clickCommentNickname:(MMUIViewController *)arg1 username:(NSString *)arg2 contact:(WCFinderContact *)arg3 isWeChatFriend:(_Bool)arg4;
- (void)clickAuthorCommentAvatarWhenInProfile:(MMUIViewController *)arg1;
@end

