//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WCFinderDownloadImageCdnMgrExt-Protocol.h"
#import "WCFinderFeedImageViewProtocol-Protocol.h"
#import "WCFinderPlayerControlViewDelegate-Protocol.h"
#import "WCPlayerDownloaderExt-Protocol.h"

@class NSString, UIImageView, UILabel, UITapGestureRecognizer, WCFinderFeedImageView, WCFinderFeedMediaWrap, WCFinderMediaInfo, WCFinderPlayerControlView, WCPlayerView;
@protocol WCFinderFeedContentMediaActionProtocol;

@interface WCFinderFeedVideoCollectionViewCell : UICollectionViewCell <WCFinderDownloadImageCdnMgrExt, WCFinderPlayerControlViewDelegate, WCFinderFeedImageViewProtocol, WCPlayerDownloaderExt, UIGestureRecognizerDelegate>
{
    _Bool _isCurrentPlaying;
    _Bool _needsRestThumb;
    _Bool _needsUpdateThumb;
    id <WCFinderFeedContentMediaActionProtocol> _delegate;
    unsigned long long _currentIndex;
    WCPlayerView *_playerView;
    WCFinderFeedImageView *_thumbImageView;
    WCFinderPlayerControlView *_playerConfigControlView;
    WCFinderFeedMediaWrap *_mediaWrap;
    WCFinderMediaInfo *_mediaInfo;
    UIImageView *_retryImageView;
    UILabel *_retryLabel;
    UITapGestureRecognizer *_likeGes;
    NSString *_currentVideoTid;
}

@property(copy, nonatomic) NSString *currentVideoTid; // @synthesize currentVideoTid=_currentVideoTid;
@property(nonatomic) _Bool needsUpdateThumb; // @synthesize needsUpdateThumb=_needsUpdateThumb;
@property(nonatomic) _Bool needsRestThumb; // @synthesize needsRestThumb=_needsRestThumb;
@property(retain, nonatomic) UITapGestureRecognizer *likeGes; // @synthesize likeGes=_likeGes;
@property(retain, nonatomic) UILabel *retryLabel; // @synthesize retryLabel=_retryLabel;
@property(retain, nonatomic) UIImageView *retryImageView; // @synthesize retryImageView=_retryImageView;
@property(nonatomic) _Bool isCurrentPlaying; // @synthesize isCurrentPlaying=_isCurrentPlaying;
@property(retain, nonatomic) WCFinderMediaInfo *mediaInfo; // @synthesize mediaInfo=_mediaInfo;
@property(retain, nonatomic) WCFinderFeedMediaWrap *mediaWrap; // @synthesize mediaWrap=_mediaWrap;
@property(retain, nonatomic) WCFinderPlayerControlView *playerConfigControlView; // @synthesize playerConfigControlView=_playerConfigControlView;
@property(retain, nonatomic) WCFinderFeedImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(retain, nonatomic) WCPlayerView *playerView; // @synthesize playerView=_playerView;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) __weak id <WCFinderFeedContentMediaActionProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)OnCdnDownloadError:(id)arg1;
- (void)OnCdnDownloadProgress:(id)arg1;
- (void)OnCdnDownloadSuccess:(id)arg1;
- (void)OnCdnVideoMoovReady:(id)arg1 WaitTime:(unsigned int)arg2 Offset:(unsigned int)arg3;
- (void)loadingRetry;
- (void)onFinderThumbDownloadFail:(id)arg1;
- (void)onFinderThumbDownloadSuccess:(id)arg1;
- (void)processIconViewVisible;
- (void)onShowBufferingView;
- (void)onVideoPlay;
- (void)onPlayToEnd;
- (void)updateCurrentVideoThumb;
- (void)resetCurrentVideoThumb;
- (double)getPlayVideoTotalTime;
- (double)getCurrentPlayVideoTime;
- (void)pauseVideoIfSupport;
- (void)changeVideoSilenceStatue:(_Bool)arg1;
- (void)stopVideoIfSupport;
- (void)onLikeFeed;
- (void)playVideoIfSupport:(double)arg1 silencePlay:(_Bool)arg2 dataScene:(long long)arg3 dataTid:(id)arg4 dataPos:(long long)arg5 fetchFeedTime:(double)arg6;
- (void)updateImage:(id)arg1;
- (struct CGSize)contentSizeForMediaInfo:(id)arg1;
- (void)resetVideoReloadHidden:(_Bool)arg1;
- (void)initVideoReloadAction;
- (void)onClickRetry:(id)arg1;
- (id)generateConfig;
- (void)changeDataSource:(id)arg1;
- (void)initSubView;
- (void)dealloc;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

