//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWindowViewController.h"

#import "WCGroupUndoneEduViewDelegate-Protocol.h"

@class NSString, UIButton, WCGroupUndoneEduView;
@protocol WCGroupUndoneEduViewDelegate;

@interface WCGroupUndoneEduWindow : MMWindowViewController <WCGroupUndoneEduViewDelegate>
{
    id <WCGroupUndoneEduViewDelegate> _undoneDelegate;
    WCGroupUndoneEduView *_contentView;
    UIButton *_backgroundBtn;
}

@property(retain, nonatomic) UIButton *backgroundBtn; // @synthesize backgroundBtn=_backgroundBtn;
@property(readonly, nonatomic) WCGroupUndoneEduView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <WCGroupUndoneEduViewDelegate> undoneDelegate; // @synthesize undoneDelegate=_undoneDelegate;
- (void).cxx_destruct;
- (void)onGUEConfirm:(id)arg1;
- (void)onGUEClose:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)setupViews;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

