//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCGroupUndoneBaseReport.h"

@interface WCGroupUndoneShareReport : WCGroupUndoneBaseReport
{
    _Bool _isOpenTodo;
    _Bool _isShowEdu;
    unsigned int _oper;
}

@property(nonatomic) unsigned int oper; // @synthesize oper=_oper;
@property(nonatomic) _Bool isShowEdu; // @synthesize isShowEdu=_isShowEdu;
@property(nonatomic) _Bool isOpenTodo; // @synthesize isOpenTodo=_isOpenTodo;
- (void)report;
- (void)invalidate;
- (_Bool)isValid;

@end

