//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;
@protocol WCPayRecommendItemViewDelegate;

@interface WCPayRecommendItemView : UIView
{
    id <WCPayRecommendItemViewDelegate> _m_delegate;
    NSArray *_numbers;
    NSMutableArray *_itemViews;
    NSMutableArray *_seperatorViews;
}

@property(retain) NSMutableArray *seperatorViews; // @synthesize seperatorViews=_seperatorViews;
@property(retain) NSMutableArray *itemViews; // @synthesize itemViews=_itemViews;
@property(retain) NSArray *numbers; // @synthesize numbers=_numbers;
@property __weak id <WCPayRecommendItemViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (void)onClickButton:(id)arg1;
- (void)addLine;
- (void)addButton:(id)arg1;
- (void)updateButtons;
- (void)updateNumbers:(id)arg1;
- (void)updateView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

