//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPlayerLoadingRequest.h"

@class AVAssetResourceLoadingRequest;

@interface WCPlayerAVLoadingRequest : WCPlayerLoadingRequest
{
    AVAssetResourceLoadingRequest *_loadingRequest;
}

@property(retain, nonatomic) AVAssetResourceLoadingRequest *loadingRequest; // @synthesize loadingRequest=_loadingRequest;
- (void).cxx_destruct;
- (void)respondWithData:(id)arg1;
- (_Bool)fillInformationWithLen:(unsigned long long)arg1 MimeType:(id)arg2;
- (void)finishLoadingWithError:(id)arg1;
- (void)finishLoading;
- (id)getLoadingRequest;
- (_Bool)isFinished;
- (_Bool)requestsAllDataToEndOfResource;
- (unsigned long long)currentOffset;
- (unsigned long long)requestedLength;
- (unsigned long long)requestedOffset;
- (id)initWithResourceLoadingRequest:(id)arg1;

@end

