//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WCRecordFBNormalView, WCRecordFBSmallView;

@interface WCRecordFeedbackView : UIView
{
    _Bool _bShowRecordingState;
    WCRecordFBSmallView *_smallFbView;
    WCRecordFBNormalView *_normalFbView;
}

@property(retain, nonatomic) WCRecordFBNormalView *normalFbView; // @synthesize normalFbView=_normalFbView;
@property(retain, nonatomic) WCRecordFBSmallView *smallFbView; // @synthesize smallFbView=_smallFbView;
@property(nonatomic) _Bool bShowRecordingState; // @synthesize bShowRecordingState=_bShowRecordingState;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (void)setPeakPower:(float)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

