//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "IContactMgrExt-Protocol.h"
#import "IStrangerBrandContactHeadImageExt-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class NSString;
@protocol WCTimelineDataProviderDelegate;

@interface WCTimelineDataProvider : MMObject <IStrangerBrandContactHeadImageExt, IContactMgrExt, PBMessageObserverDelegate>
{
    unsigned long long uiClientLatestID;
    NSString *fpHash;
    _Bool isWorking;
    id <WCTimelineDataProviderDelegate> delegate;
}

@property(nonatomic) __weak id <WCTimelineDataProviderDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)saveServerSession:(id)arg1;
- (void)parsePattern:(id)arg1;
- (void)updateConfig:(id)arg1 isFirstPage:(_Bool)arg2;
- (void)reportKVStatSightRecieveWithMeidaItem:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)responseForSnsTimeLineResponse:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)requestForSnsTimeLineRequest:(unsigned long long)arg1 minId:(unsigned long long)arg2 lastRequestTime:(unsigned int)arg3 isPrePage:(_Bool)arg4;
- (_Bool)requestForSnsTimeLineRequest:(unsigned long long)arg1 minId:(unsigned long long)arg2 lastRequestTime:(unsigned int)arg3;
- (int)getNetworkType;
- (id)converListToList:(id)arg1;
- (void)meggeObjectOperation:(id)arg1 snsObject:(id)arg2;
- (void)dealloc;
- (void)SafeMD5;
- (id)init;
- (unsigned int)onServiceCleanCache;
- (_Bool)updateNextPage:(unsigned long long)arg1 bottomId:(unsigned long long)arg2 minChangedTime:(unsigned int)arg3;
- (_Bool)updatePrePage:(unsigned long long)arg1;
- (_Bool)updateFirstPage:(unsigned long long)arg1;
- (void)preDownloadCanvasDataItemResrc:(id)arg1;
- (void)changeAdTimeForPosition:(id)arg1 retList:(id)arg2;
- (void)delAdList:(id)arg1 retAdList:(id)arg2;
- (void)addUbdXmlAdtoAdList:(id)arg1;
- (void)addRecList:(id)arg1 toAdList:(id)arg2;
- (void)clearSnsAdExpInfo:(id)arg1;
- (void)onBrandContactHeadImageURLChange:(id)arg1;
- (void)onStrangerBrandHeadImageURLChange:(id)arg1;
- (void)updateAdvertiserInfo:(id)arg1;
- (void)doQADIDReport:(id)arg1;
- (_Bool)isAdCommentOrLikeBySelf:(id)arg1;
- (void)dumpAllNewAdList:(id)arg1;
- (void)delAdWithSnsId:(id)arg1 SnsId:(id)arg2;
- (id)convertServerRecList2List:(id)arg1;
- (id)converServerAdList2List:(id)arg1;
- (_Bool)hasExistAdItem:(id)arg1;
- (id)convertAdvertiseMsgListToList;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

