//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableArray, NSString;

@interface WCTimelineMissReadJumpBtnExposureRecord : MMObject
{
    unsigned int _exposureCount;
    unsigned int _clickCount;
    unsigned int _jumpBtnId;
    unsigned int _jumpBtnClickType;
    NSString *_sessionId;
    NSMutableArray *_newerFeedIds;
    NSMutableArray *_exposureFeedIds;
    unsigned long long _missReadRecordCount;
    unsigned long long _jumpableMissReadRecordCount;
}

@property(nonatomic) unsigned int jumpBtnClickType; // @synthesize jumpBtnClickType=_jumpBtnClickType;
@property(nonatomic) unsigned int jumpBtnId; // @synthesize jumpBtnId=_jumpBtnId;
@property(nonatomic) unsigned int clickCount; // @synthesize clickCount=_clickCount;
@property(nonatomic) unsigned int exposureCount; // @synthesize exposureCount=_exposureCount;
@property(nonatomic) unsigned long long jumpableMissReadRecordCount; // @synthesize jumpableMissReadRecordCount=_jumpableMissReadRecordCount;
@property(nonatomic) unsigned long long missReadRecordCount; // @synthesize missReadRecordCount=_missReadRecordCount;
@property(retain, nonatomic) NSMutableArray *exposureFeedIds; // @synthesize exposureFeedIds=_exposureFeedIds;
@property(retain, nonatomic) NSMutableArray *newerFeedIds; // @synthesize newerFeedIds=_newerFeedIds;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;

@end

