//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCContentItemBaseView.h"

#import "WCSightViewDelegate-Protocol.h"

@class NSString, UIButton, WCTimeLineAdFullCardSightView;

@interface WCTimeLineAdFullCardView : WCContentItemBaseView <WCSightViewDelegate>
{
    UIButton *_adTouchButton;
    WCTimeLineAdFullCardSightView *_sightView;
}

+ (double)heightForMedia:(id)arg1;
@property(retain, nonatomic) WCTimeLineAdFullCardSightView *sightView; // @synthesize sightView=_sightView;
@property(retain, nonatomic) UIButton *adTouchButton; // @synthesize adTouchButton=_adTouchButton;
- (void).cxx_destruct;
- (void)dealloc;
- (void)onClickFromGesture:(long long)arg1;
- (void)contentItemDidEndDisplaying;
- (void)onClick:(long long)arg1;
- (void)delayClearTouchButtonColor;
- (void)delayClickAdTouchButton;
- (id)getVoiceOverStrForTimeline;
- (void)onVoiceOverClick;
- (void)onClickAdTouchButton:(id)arg1 forEvent:(id)arg2;
- (void)updateTouchButtonHighlightedVisible:(_Bool)arg1;
- (void)addButtonForItem:(id)arg1;
- (void)autoPauseWithoutSound;
- (void)autoPlayWithoutSound;
- (void)addSightViewWithMediaItem:(id)arg1;
- (void)initSightAndCoverView:(id)arg1;
- (void)addImageViewWithMediaItem:(id)arg1;
- (void)addMediaViewForItem:(id)arg1;
- (void)initViewsWithWCDataItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

