//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITPPlayerDelegate-Protocol.h"

@class NSString, TPVideoInfo, UIView;
@protocol ITPPlayer, OS_dispatch_source, WCTPPlayerDelegate;

@interface WCTPPlayer : NSObject <ITPPlayerDelegate>
{
    _Bool _outputVideoFrame;
    _Bool _outputAudioFrame;
    _Bool _muted;
    _Bool _bInitialSeekAccurate;
    _Bool _bBeginFrameRendered;
    _Bool _bStopped;
    _Bool _isLoopback;
    _Bool _isPrepared;
    float _expectBufferLen;
    float _playbackInterval;
    float _initialSeekPos;
    id <WCTPPlayerDelegate> _delegate;
    UIView *_displayView;
    id <ITPPlayer> _player;
    NSObject<OS_dispatch_source> *_dispatchTimer;
    long long _downloadType;
    CDUnknownBlockType _intervalCallBackBlock;
    NSString *_resourceUrl;
    NSString *_playerIdentifier;
    TPVideoInfo *_videoInfo;
}

@property(retain, nonatomic) TPVideoInfo *videoInfo; // @synthesize videoInfo=_videoInfo;
@property(retain, nonatomic) NSString *playerIdentifier; // @synthesize playerIdentifier=_playerIdentifier;
@property(retain, nonatomic) NSString *resourceUrl; // @synthesize resourceUrl=_resourceUrl;
@property(nonatomic) _Bool isPrepared; // @synthesize isPrepared=_isPrepared;
@property(nonatomic) _Bool isLoopback; // @synthesize isLoopback=_isLoopback;
@property _Bool bStopped; // @synthesize bStopped=_bStopped;
@property(nonatomic) _Bool bBeginFrameRendered; // @synthesize bBeginFrameRendered=_bBeginFrameRendered;
@property(nonatomic) _Bool bInitialSeekAccurate; // @synthesize bInitialSeekAccurate=_bInitialSeekAccurate;
@property(nonatomic) float initialSeekPos; // @synthesize initialSeekPos=_initialSeekPos;
@property(copy, nonatomic) CDUnknownBlockType intervalCallBackBlock; // @synthesize intervalCallBackBlock=_intervalCallBackBlock;
@property(nonatomic) long long downloadType; // @synthesize downloadType=_downloadType;
@property(nonatomic) float playbackInterval; // @synthesize playbackInterval=_playbackInterval;
@property(retain) NSObject<OS_dispatch_source> *dispatchTimer; // @synthesize dispatchTimer=_dispatchTimer;
@property(retain, nonatomic) id <ITPPlayer> player; // @synthesize player=_player;
@property(nonatomic) __weak UIView *displayView; // @synthesize displayView=_displayView;
@property(nonatomic) float expectBufferLen; // @synthesize expectBufferLen=_expectBufferLen;
@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
@property(nonatomic) _Bool outputAudioFrame; // @synthesize outputAudioFrame=_outputAudioFrame;
@property(nonatomic) _Bool outputVideoFrame; // @synthesize outputVideoFrame=_outputVideoFrame;
@property(nonatomic) __weak id <WCTPPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onVideoSizeChanged:(id)arg1 width:(int)arg2 height:(int)arg3;
- (void)onPlayer:(id)arg1 audioFrameOut:(id)arg2;
- (void)onPlayer:(id)arg1 videoFrameOut:(id)arg2;
- (void)onPlayer:(id)arg1 subtitleData:(id)arg2;
- (void)onPlayer:(id)arg1 info:(unsigned long long)arg2 extra1:(long long)arg3 extra2:(long long)arg4 extraObject:(id)arg5;
- (void)onSeekComplete:(id)arg1;
- (void)onPlayer:(id)arg1 errorType:(long long)arg2 errorCode:(long long)arg3 arg1:(long long)arg4 arg2:(long long)arg5;
- (void)onPrepared:(id)arg1;
- (void)onCompletion:(id)arg1;
- (void)stopTimer;
- (void)startTimer;
- (void)onStartRenderFrame;
- (long long)getAudioCodecID;
- (long long)getVideoCodecID;
- (void)setContentMode:(long long)arg1;
- (void)captureVideoWithFinishBlock:(CDUnknownBlockType)arg1;
- (id)syncCaptureVideo;
- (float)playbackPos;
- (float)bufferPos;
- (void)setAllowsExternalPlayback:(_Bool)arg1;
- (void)setLoopback:(_Bool)arg1;
- (long long)audioBitrate;
- (long long)videoBitrate;
- (struct CGSize)presentationSize;
- (float)duration;
- (void)setPlayerOptionalParams;
- (void)seekTo:(double)arg1 AccurateSeek:(_Bool)arg2;
- (void)seekTo:(double)arg1;
- (void)seekBeigin;
- (void)addPeriodicTimeObserverForInterval:(float)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)pause;
- (void)play;
- (void)prepareAsync;
- (void)cleanPlayer;
- (void)createPlayer;
- (_Bool)isPlaying;
- (long long)playerState;
@property(nonatomic) float playSpeedRatio; // @dynamic playSpeedRatio;
- (void)setVideoInfo;
- (void)setResourceloaderDelegate:(id)arg1;
- (void)setInitialSeekPos:(float)arg1 Accurate:(_Bool)arg2;
- (void)setPlayerDisplayView:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

