//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface WCWeAppInfo : NSObject <NSCoding>
{
    NSString *appUserName;
    NSString *pagePath;
    unsigned int _version;
    unsigned int _debugMode;
    NSString *_shareActionId;
}

@property(retain, nonatomic) NSString *shareActionId; // @synthesize shareActionId=_shareActionId;
@property(nonatomic) unsigned int debugMode; // @synthesize debugMode=_debugMode;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *pagePath; // @synthesize pagePath;
@property(retain, nonatomic) NSString *appUserName; // @synthesize appUserName;
- (void).cxx_destruct;
- (_Bool)isValid;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

