//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAJSEventHandlerContextDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSMutableSet, NSString, WAJSCoreService, WKWebView;

@interface WeAppWorker : NSObject <WAJSEventHandlerContextDelegate, WKUIDelegate, WKNavigationDelegate>
{
    WKWebView *_context;
    unsigned int _workerId;
    int _bufferId;
    WAJSCoreService *_service;
    NSMutableSet *_eventHandlers;
    NSString *_userFile;
    long long _dataSize;
}

@property long long dataSize; // @synthesize dataSize=_dataSize;
@property(retain) NSString *userFile; // @synthesize userFile=_userFile;
@property(retain) NSMutableSet *eventHandlers; // @synthesize eventHandlers=_eventHandlers;
@property(nonatomic) int bufferId; // @synthesize bufferId=_bufferId;
@property(nonatomic) unsigned int workerId; // @synthesize workerId=_workerId;
@property(nonatomic) __weak WAJSCoreService *service; // @synthesize service=_service;
- (void).cxx_destruct;
- (id)getBase64Buffer;
- (void)setListenBuffer:(int)arg1;
- (id)GetWebViewPluginByName:(id)arg1;
- (id)getEventHandler:(id)arg1;
- (void)endWithResult:(id)arg1 handler:(id)arg2;
- (id)getAppId;
- (void)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)stopWorker;
- (void)sendMessage:(id)arg1;
- (void)initJSContext:(id)arg1;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)initWebView;
- (void)dealloc;
- (id)init:(id)arg1 workerId:(unsigned int)arg2 service:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

