//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WebviewJSEventHandlerBase.h"

@interface WebviewJSEventHandler_getGameCommInfo : WebviewJSEventHandlerBase
{
}

- (id)readLocalResItemBackup:(id)arg1;
- (_Bool)backupLocalResItem:(id)arg1 key:(id)arg2;
- (id)checkWebResourceValidation:(id)arg1;
- (id)saveWebResource:(id)arg1;
- (id)extractLocalIds:(id)arg1;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;

@end

