//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WPUtility : NSObject
{
}

+ (long long)getDecodeeTypeWith:(long long)arg1;
+ (id)stringWithPlayerDecoderType:(long long)arg1;
+ (id)getLibraryCachePath;
+ (id)getLogDirPath;
+ (id)getWritingLogDirPath;
+ (_Bool)isiOS13plus;
+ (unsigned long long)genCurrentTimeInMsFrom1970;
+ (unsigned long long)genCurrentTimeInMs;
+ (unsigned int)genCurrentTime;

@end

