//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WSTemplateBaseJSHandler.h"

@protocol WSPardusWebViewJSHandlerDelegate;

@interface WSPardusWebViewJSHandler : WSTemplateBaseJSHandler
{
    id <WSPardusWebViewJSHandlerDelegate> _logicDelegate;
}

@property(nonatomic) __weak id <WSPardusWebViewJSHandlerDelegate> logicDelegate; // @synthesize logicDelegate=_logicDelegate;
- (void).cxx_destruct;
- (void)sendPardusActionCallBackToWeb:(id)arg1;
- (void)sendPardusCommDataReadyToWeb:(id)arg1;
- (void)sendPardusDataToWeb:(id)arg1;
- (void)webViewContentProcessDidTerminate:(id)arg1;
- (void)handleJSApi_openWebSearch:(id)arg1 callbackId:(id)arg2;
- (void)handleActionReport:(unsigned int)arg1 pos:(unsigned int)arg2 info:(id)arg3;
- (void)handlePardusAction:(id)arg1 callbackId:(id)arg2;
- (void)handlePardusReport:(id)arg1 callbackId:(id)arg2;
- (_Bool)onJsApiHandlerForwardDealWithFunc:(id)arg1 params:(id)arg2 callbackID:(id)arg3;
- (id)jsEventsNeedRegister;

@end

