//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface XMBaseAttachData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *code; // @dynamic code;
@property(retain, nonatomic) NSString *downloadurl; // @dynamic downloadurl;
@property(retain, nonatomic) NSString *fileid; // @dynamic fileid;
@property(retain, nonatomic) NSString *key; // @dynamic key;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) unsigned int size; // @dynamic size;
@property(retain, nonatomic) NSString *type; // @dynamic type;

@end

