//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface ZZBaseViewChainModel : NSObject
{
    long long _tag;
    UIView *_view;
    Class _viewClass;
}

@property(readonly, nonatomic) Class viewClass; // @synthesize viewClass=_viewClass;
@property(readonly, nonatomic) UIView *view; // @synthesize view=_view;
@property(readonly, nonatomic) long long tag; // @synthesize tag=_tag;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) CDUnknownBlockType transform;
@property(readonly, copy, nonatomic) CDUnknownBlockType shadowRadius;
@property(readonly, copy, nonatomic) CDUnknownBlockType shadowOffset;
@property(readonly, copy, nonatomic) CDUnknownBlockType shadowOpacity;
@property(readonly, copy, nonatomic) CDUnknownBlockType shadowColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType shadow;
@property(readonly, copy, nonatomic) CDUnknownBlockType anchorPoint;
@property(readonly, copy, nonatomic) CDUnknownBlockType zPosition;
@property(readonly, copy, nonatomic) CDUnknownBlockType borderColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType borderWidth;
@property(readonly, copy, nonatomic) CDUnknownBlockType border;
@property(readonly, copy, nonatomic) CDUnknownBlockType cornerRadius;
@property(readonly, copy, nonatomic) CDUnknownBlockType masksToBounds;
@property(readonly, copy, nonatomic) CDUnknownBlockType multipleTouchEnabled;
@property(readonly, copy, nonatomic) CDUnknownBlockType userInteractionEnabled;
@property(readonly, copy, nonatomic) CDUnknownBlockType clipsToBounds;
@property(readonly, copy, nonatomic) CDUnknownBlockType hidden;
@property(readonly, copy, nonatomic) CDUnknownBlockType opaque;
@property(readonly, copy, nonatomic) CDUnknownBlockType contentMode;
@property(readonly, copy, nonatomic) CDUnknownBlockType alpha;
@property(readonly, copy, nonatomic) CDUnknownBlockType tintColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType backgroundColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType remakeMasonry;
@property(readonly, copy, nonatomic) CDUnknownBlockType updateMasonry;
@property(readonly, copy, nonatomic) CDUnknownBlockType masonry;
@property(readonly, copy, nonatomic) CDUnknownBlockType right;
@property(readonly, copy, nonatomic) CDUnknownBlockType left;
@property(readonly, copy, nonatomic) CDUnknownBlockType bottom;
@property(readonly, copy, nonatomic) CDUnknownBlockType top;
@property(readonly, copy, nonatomic) CDUnknownBlockType centerY;
@property(readonly, copy, nonatomic) CDUnknownBlockType centerX;
@property(readonly, copy, nonatomic) CDUnknownBlockType center;
@property(readonly, copy, nonatomic) CDUnknownBlockType height;
@property(readonly, copy, nonatomic) CDUnknownBlockType width;
@property(readonly, copy, nonatomic) CDUnknownBlockType size;
@property(readonly, copy, nonatomic) CDUnknownBlockType y;
@property(readonly, copy, nonatomic) CDUnknownBlockType x;
@property(readonly, copy, nonatomic) CDUnknownBlockType origin;
@property(readonly, copy, nonatomic) CDUnknownBlockType frame;
- (id)initWithTag:(long long)arg1 andView:(id)arg2;

@end

