//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZZControlTarget : NSObject
{
    CDUnknownBlockType _senderBlock;
    unsigned long long _controlEvents;
}

@property(nonatomic) unsigned long long controlEvents; // @synthesize controlEvents=_controlEvents;
@property(copy, nonatomic) CDUnknownBlockType senderBlock; // @synthesize senderBlock=_senderBlock;
- (void).cxx_destruct;
- (void)senderMethod:(id)arg1;
- (id)initWithSenderBlock:(CDUnknownBlockType)arg1 controlEvents:(unsigned long long)arg2;

@end

