//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZZFLEXAngelSectionBaseChainModel.h"

@class NSArray;

@interface ZZFLEXAngelSectionEditChainModel : ZZFLEXAngelSectionBaseChainModel
{
}

- (CDUnknownBlockType)updateAllCellsByTag;
- (CDUnknownBlockType)updateCellByTag;
- (CDUnknownBlockType)updateFooter;
- (CDUnknownBlockType)updateHeader;
- (CDUnknownBlockType)updateCells;
- (CDUnknownBlockType)updateItems;
- (CDUnknownBlockType)update;
- (CDUnknownBlockType)deleteAllCellsByTag;
- (CDUnknownBlockType)deleteCellByTag;
- (CDUnknownBlockType)deleteFooter;
- (CDUnknownBlockType)deleteHeader;
- (CDUnknownBlockType)clearCells;
- (CDUnknownBlockType)clearItems;
- (CDUnknownBlockType)clear;
- (CDUnknownBlockType)dataModelArrayByViewTag;
- (CDUnknownBlockType)dataModelByViewTag;
@property(readonly, nonatomic) id dataModelForFooter;
@property(readonly, nonatomic) id dataModelForHeader;
@property(readonly, nonatomic) NSArray *dataModelArray;

@end

