//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZZFLEXAngelViewBaseBatchChainModel.h"

@interface ZZFLEXAngelViewBatchInsertChainModel : ZZFLEXAngelViewBaseBatchChainModel
{
    long long _status;
    long long _insertTag;
}

@property(nonatomic) long long insertTag; // @synthesize insertTag=_insertTag;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void)p_tryInsertCells;
- (CDUnknownBlockType)afterCell;
- (CDUnknownBlockType)beforeCell;
- (CDUnknownBlockType)toIndex;
- (CDUnknownBlockType)toSection;
- (CDUnknownBlockType)withDataModelArray;

@end

