//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class UICollectionView, UICollectionViewLayout, UIColor;

@protocol ZZFlexibleLayoutFlowLayoutDelegate <UICollectionViewDelegateFlowLayout>
- (_Bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 didSectionFooterPinToVisibleBounds:(long long)arg3;
- (_Bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 didSectionHeaderPinToVisibleBounds:(long long)arg3;
- (UIColor *)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 colorForSectionAtIndex:(long long)arg3;
@end

