//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, ZZFlexibleLayoutSectionModel;

@interface ZZFLEXAngelViewBaseBatchChainModel : NSObject
{
    Class _viewClass;
    NSMutableArray *_listData;
    NSMutableArray *_viewModelArray;
    ZZFlexibleLayoutSectionModel *_sectionModel;
    id _itemsDelegate;
    CDUnknownBlockType _itemsEventAction;
    CDUnknownBlockType _itemsSelectedAction;
    CDUnknownBlockType _itemsConfigAction;
    long long _tag;
    struct CGSize _itemViewSize;
}

@property(nonatomic) struct CGSize itemViewSize; // @synthesize itemViewSize=_itemViewSize;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(copy, nonatomic) CDUnknownBlockType itemsConfigAction; // @synthesize itemsConfigAction=_itemsConfigAction;
@property(copy, nonatomic) CDUnknownBlockType itemsSelectedAction; // @synthesize itemsSelectedAction=_itemsSelectedAction;
@property(copy, nonatomic) CDUnknownBlockType itemsEventAction; // @synthesize itemsEventAction=_itemsEventAction;
@property(nonatomic) __weak id itemsDelegate; // @synthesize itemsDelegate=_itemsDelegate;
@property(retain, nonatomic) ZZFlexibleLayoutSectionModel *sectionModel; // @synthesize sectionModel=_sectionModel;
@property(retain, nonatomic) NSMutableArray *viewModelArray; // @synthesize viewModelArray=_viewModelArray;
@property(retain, nonatomic) NSMutableArray *listData; // @synthesize listData=_listData;
@property(nonatomic) Class viewClass; // @synthesize viewClass=_viewClass;
- (void).cxx_destruct;
- (void)setItemConfigAction:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)viewHeight;
- (CDUnknownBlockType)viewSize;
- (CDUnknownBlockType)viewTag;
- (CDUnknownBlockType)configAction;
- (CDUnknownBlockType)selectedAction;
- (CDUnknownBlockType)eventAction;
- (CDUnknownBlockType)delegate;
- (CDUnknownBlockType)withDataModelArray;
- (CDUnknownBlockType)toSection;
- (id)initWithViewClass:(Class)arg1 listData:(id)arg2;

@end

