//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZZFlexibleLayoutSectionModel;

@interface ZZFLEXAngelSectionBaseChainModel : NSObject
{
    ZZFlexibleLayoutSectionModel *_sectionModel;
}

@property(retain, nonatomic) ZZFlexibleLayoutSectionModel *sectionModel; // @synthesize sectionModel=_sectionModel;
- (void).cxx_destruct;
- (CDUnknownBlockType)backgrounColor;
- (CDUnknownBlockType)sectionInsets;
- (CDUnknownBlockType)minimumInteritemSpacing;
- (CDUnknownBlockType)minimumLineSpacing;
- (id)initWithSectionModel:(id)arg1;

@end

