//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSIndexPath;

@protocol ZZFlexibleLayoutViewProtocol <NSObject>

@optional
+ (double)viewHeightByDataModel:(id)arg1;
+ (struct CGSize)viewSizeByDataModel:(id)arg1;
- (void)onViewPositionUpdatedWithIndexPath:(NSIndexPath *)arg1 sectionItemCount:(long long)arg2;
- (void)setViewEventAction:(id (^)(long long, id))arg1;
- (void)setViewDelegate:(id)arg1;
- (void)setViewDataModel:(id)arg1;
@end

