//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CAShapeLayer, UIColor;

@interface ZZSeparatorModel : NSObject
{
    CAShapeLayer *_layer;
    UIColor *_color;
    long long _position;
    double _borderWidth;
    double _offset;
    double _begin;
    double _end;
    double _length;
}

@property(nonatomic) double length; // @synthesize length=_length;
@property(nonatomic) double end; // @synthesize end=_end;
@property(nonatomic) double begin; // @synthesize begin=_begin;
@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) long long position; // @synthesize position=_position;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
@property(readonly, nonatomic) CAShapeLayer *layer; // @synthesize layer=_layer;
- (id)init;

@end

