//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZZBaseViewChainModel.h"

@interface ZZTableViewChainModel : ZZBaseViewChainModel
{
}

@property(readonly, copy, nonatomic) CDUnknownBlockType scrollsToTop;
@property(readonly, copy, nonatomic) CDUnknownBlockType showsVerticalScrollIndicator;
@property(readonly, copy, nonatomic) CDUnknownBlockType showsHorizontalScrollIndicator;
@property(readonly, copy, nonatomic) CDUnknownBlockType scrollEnabled;
@property(readonly, copy, nonatomic) CDUnknownBlockType pagingEnabled;
@property(readonly, copy, nonatomic) CDUnknownBlockType alwaysBounceHorizontal;
@property(readonly, copy, nonatomic) CDUnknownBlockType alwaysBounceVertical;
@property(readonly, copy, nonatomic) CDUnknownBlockType bounces;
@property(readonly, copy, nonatomic) CDUnknownBlockType contentInset;
@property(readonly, copy, nonatomic) CDUnknownBlockType contentOffset;
@property(readonly, copy, nonatomic) CDUnknownBlockType contentSize;
@property(readonly, copy, nonatomic) CDUnknownBlockType sectionIndexColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType sectionIndexBackgroundColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType tableFooterView;
@property(readonly, copy, nonatomic) CDUnknownBlockType tableHeaderView;
@property(readonly, copy, nonatomic) CDUnknownBlockType separatorColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType separatorStyle;
@property(readonly, copy, nonatomic) CDUnknownBlockType allowsMultipleSelectionDuringEditing;
@property(readonly, copy, nonatomic) CDUnknownBlockType allowsSelectionDuringEditing;
@property(readonly, copy, nonatomic) CDUnknownBlockType allowsMultipleSelection;
@property(readonly, copy, nonatomic) CDUnknownBlockType allowsSelection;
@property(readonly, copy, nonatomic) CDUnknownBlockType editing;
@property(readonly, copy, nonatomic) CDUnknownBlockType separatorInset;
@property(readonly, copy, nonatomic) CDUnknownBlockType estimatedSectionFooterHeight;
@property(readonly, copy, nonatomic) CDUnknownBlockType estimatedSectionHeaderHeight;
@property(readonly, copy, nonatomic) CDUnknownBlockType estimatedRowHeight;
@property(readonly, copy, nonatomic) CDUnknownBlockType sectionFooterHeight;
@property(readonly, copy, nonatomic) CDUnknownBlockType sectionHeaderHeight;
@property(readonly, copy, nonatomic) CDUnknownBlockType rowHeight;
@property(readonly, copy, nonatomic) CDUnknownBlockType dataSource;
@property(readonly, copy, nonatomic) CDUnknownBlockType delegate;

@end

