//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZZBaseViewChainModel.h"

@interface ZZTextViewChainModel : ZZBaseViewChainModel
{
}

@property(readonly, copy, nonatomic) CDUnknownBlockType scrollsToTop;
@property(readonly, copy, nonatomic) CDUnknownBlockType showsVerticalScrollIndicator;
@property(readonly, copy, nonatomic) CDUnknownBlockType showsHorizontalScrollIndicator;
@property(readonly, copy, nonatomic) CDUnknownBlockType scrollEnabled;
@property(readonly, copy, nonatomic) CDUnknownBlockType pagingEnabled;
@property(readonly, copy, nonatomic) CDUnknownBlockType alwaysBounceHorizontal;
@property(readonly, copy, nonatomic) CDUnknownBlockType alwaysBounceVertical;
@property(readonly, copy, nonatomic) CDUnknownBlockType bounces;
@property(readonly, copy, nonatomic) CDUnknownBlockType contentInset;
@property(readonly, copy, nonatomic) CDUnknownBlockType contentOffset;
@property(readonly, copy, nonatomic) CDUnknownBlockType contentSize;
@property(readonly, copy, nonatomic) CDUnknownBlockType linkTextAttributes;
@property(readonly, copy, nonatomic) CDUnknownBlockType textContainerInset;
@property(readonly, copy, nonatomic) CDUnknownBlockType clearsOnInsertion;
@property(readonly, copy, nonatomic) CDUnknownBlockType typingAttributes;
@property(readonly, copy, nonatomic) CDUnknownBlockType attributedText;
@property(readonly, copy, nonatomic) CDUnknownBlockType allowsEditingTextAttributes;
@property(readonly, copy, nonatomic) CDUnknownBlockType keyboardType;
@property(readonly, copy, nonatomic) CDUnknownBlockType dataDetectorTypes;
@property(readonly, copy, nonatomic) CDUnknownBlockType selectable;
@property(readonly, copy, nonatomic) CDUnknownBlockType editable;
@property(readonly, copy, nonatomic) CDUnknownBlockType selectedRange;
@property(readonly, copy, nonatomic) CDUnknownBlockType textAlignment;
@property(readonly, copy, nonatomic) CDUnknownBlockType textColor;
@property(readonly, copy, nonatomic) CDUnknownBlockType font;
@property(readonly, copy, nonatomic) CDUnknownBlockType text;
@property(readonly, copy, nonatomic) CDUnknownBlockType delegate;

@end

